/* eslint-disable */
export interface Automation {
  slug: string;
  title: string;
  industry: string;
  color: string;
  stat: string;
  desc: string;
  problem: string;
  howItWorks: { step: string; desc: string }[];
  results: { big: string; label: string }[];
  techStack: string[];
  related: string[];
}

export const AUTOMATIONS: Automation[] = [
  {
    slug: 'ai-lead-response',
    title: 'AI Lead Response',
    industry: 'Real Estate',
    color: '#f9ca00',
    stat: '90s',
    desc: 'Instant AI-powered lead qualification and WhatsApp response for every inbound enquiry.',
    problem: 'Sales teams were losing leads to competitors who responded faster. Manual response times averaged 4+ hours, and agents spent most of their day copy-pasting templates and updating CRM records.',
    howItWorks: [
      { step: 'Trigger', desc: 'New lead arrives via web form, WhatsApp, Bayut, or PropertyFinder' },
      { step: 'Process', desc: 'GPT-4o reads intent, budget, timeline and scores the lead 1–100' },
      { step: 'Output', desc: 'Personalised WhatsApp + email sent in the lead\'s language within 90 seconds' },
      { step: 'Notify', desc: 'Best-match agent notified with full lead context and score in HubSpot' },
    ],
    results: [{ big: '90s', label: 'Avg response time' }, { big: '94%', label: 'Auto-handled' }, { big: '+38%', label: 'Qualified leads/mo' }],
    techStack: ['GPT-4o', 'WhatsApp Business API', 'n8n', 'HubSpot', 'Node.js'],
    related: ['tenant-screening', 'property-listing-sync', 'booking-confirmation-flow'],
  },
  {
    slug: 'invoice-document-ai',
    title: 'Invoice & Document AI',
    industry: 'Finance / Legal',
    color: '#00c8ff',
    stat: '98%',
    desc: 'Automated invoice extraction, validation, and approval routing — zero manual data entry.',
    problem: 'Finance teams were manually keying invoice data from PDFs into accounting systems, taking 15–20 minutes per invoice and introducing frequent errors. Approval chains were tracked by email.',
    howItWorks: [
      { step: 'Trigger', desc: 'Invoice PDF arrives via email or upload portal' },
      { step: 'Process', desc: 'AI extracts vendor, amounts, line items, VAT with 98%+ accuracy' },
      { step: 'Output', desc: 'Structured data pushed to accounting system with validation flags' },
      { step: 'Notify', desc: 'Approver notified via Slack/email with one-click approve/reject' },
    ],
    results: [{ big: '98%', label: 'Extraction accuracy' }, { big: '15min→45s', label: 'Per invoice' }, { big: '0', label: 'Manual data entry' }],
    techStack: ['GPT-4o Vision', 'Python', 'n8n', 'QuickBooks API', 'Slack'],
    related: ['contract-renewal-alerts', 'regulatory-compliance-monitor', 'revenue-leakage-detector'],
  },
  {
    slug: 'kpi-dashboard-report',
    title: 'KPI Dashboard Auto-Report',
    industry: 'All sectors',
    color: '#b06eff',
    stat: '6h→0',
    desc: 'Automated weekly KPI reports delivered to your inbox — no spreadsheet assembly required.',
    problem: 'Management teams spent 6+ hours every Monday pulling data from multiple systems, formatting it into slides, and emailing reports. The data was often stale by the time it was sent.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled every Monday 7am (or custom frequency)' },
      { step: 'Process', desc: 'Pulls live data from CRM, ad platforms, analytics, and finance systems' },
      { step: 'Output', desc: 'Generates branded PDF/HTML report with charts and commentary' },
      { step: 'Notify', desc: 'Delivered to email list and posted to Slack channel automatically' },
    ],
    results: [{ big: '0h', label: 'Manual report time' }, { big: '7am', label: 'Monday delivery' }, { big: '100%', label: 'Data freshness' }],
    techStack: ['n8n', 'Google Sheets API', 'HubSpot', 'Slack', 'Puppeteer'],
    related: ['revenue-leakage-detector', 'ai-lead-response', 'client-onboarding-pipeline'],
  },
  {
    slug: 'client-onboarding-pipeline',
    title: 'Client Onboarding Pipeline',
    industry: 'Professional Services',
    color: '#00ff9d',
    stat: '2d→15m',
    desc: 'Fully automated client onboarding from contract signature to first meeting in 15 minutes.',
    problem: 'New client setup took 2 days of manual work: creating accounts, sending welcome documents, scheduling meetings, setting up project tools, and updating the CRM — all done by hand.',
    howItWorks: [
      { step: 'Trigger', desc: 'Contract signed via DocuSign or equivalent' },
      { step: 'Process', desc: 'Creates client folder, sets up project board, generates credentials' },
      { step: 'Output', desc: 'Welcome email with documents and meeting link sent automatically' },
      { step: 'Notify', desc: 'Team notified with client brief and kickoff meeting added to calendar' },
    ],
    results: [{ big: '15m', label: 'Onboarding time' }, { big: '0', label: 'Manual steps' }, { big: '+28%', label: 'Client satisfaction' }],
    techStack: ['n8n', 'DocuSign', 'HubSpot', 'Notion API', 'Google Calendar'],
    related: ['kpi-dashboard-report', 'contract-renewal-alerts', 'hr-onboarding-bot'],
  },
  {
    slug: 'iot-alert-escalation',
    title: 'IoT Alert & Escalation',
    industry: 'Agriculture / Industrial',
    color: '#f9ca00',
    stat: '3 prevented',
    desc: 'Real-time IoT sensor monitoring with intelligent alert escalation — zero missed critical events.',
    problem: 'Equipment failures and out-of-range sensor readings were going unnoticed for hours, causing crop losses and production downtime. Alert emails were lost in overflowing inboxes.',
    howItWorks: [
      { step: 'Trigger', desc: 'Sensor reading exceeds threshold or connection lost' },
      { step: 'Process', desc: 'AI classifies severity, checks history, and decides escalation level' },
      { step: 'Output', desc: 'Tiered alerts: Slack for minor, WhatsApp for major, phone call for critical' },
      { step: 'Notify', desc: 'Incident logged automatically with timestamp, sensor ID, and reading' },
    ],
    results: [{ big: '3', label: 'Failures prevented' }, { big: '<30s', label: 'Alert latency' }, { big: '0', label: 'Missed critical events' }],
    techStack: ['MQTT', 'Node.js', 'n8n', 'WhatsApp API', 'PostgreSQL'],
    related: ['crop-monitoring-alert', 'support-ticket-triage', 'kpi-dashboard-report'],
  },
  {
    slug: 'marketplace-price-sync',
    title: 'Marketplace Price Sync',
    industry: 'E-commerce',
    color: '#00c8ff',
    stat: '99.9%',
    desc: 'Real-time price synchronisation across all marketplaces — no more manual listing updates.',
    problem: 'Teams were spending hours daily updating prices and stock levels across Amazon, Noon, and the own website. Price discrepancies were causing order cancellations and customer complaints.',
    howItWorks: [
      { step: 'Trigger', desc: 'Price or stock change detected in master catalogue or ERP' },
      { step: 'Process', desc: 'Maps product IDs across platforms and formats per marketplace spec' },
      { step: 'Output', desc: 'Updates pushed to all active channels within 60 seconds' },
      { step: 'Notify', desc: 'Sync report generated daily with error flagging for failed updates' },
    ],
    results: [{ big: '99.9%', label: 'Sync accuracy' }, { big: '60s', label: 'Update latency' }, { big: '-82%', label: 'Price error rate' }],
    techStack: ['n8n', 'Amazon SP-API', 'Shopify API', 'Node.js', 'PostgreSQL'],
    related: ['supplier-quote-aggregator', 'ai-lead-response', 'revenue-leakage-detector'],
  },
  {
    slug: 'tenant-screening',
    title: 'Tenant Screening Automation',
    industry: 'Real Estate',
    color: '#b06eff',
    stat: '4h→20m',
    desc: 'Automated tenant application processing, document verification, and score reporting.',
    problem: 'Property managers spent 4+ hours per application collecting documents, running checks, and compiling reports. Inconsistent screening criteria led to compliance risks.',
    howItWorks: [
      { step: 'Trigger', desc: 'Tenant application submitted via online form' },
      { step: 'Process', desc: 'Documents collected, identity verified, credit/employment checks run' },
      { step: 'Output', desc: 'Standardised screening report with pass/review/decline recommendation' },
      { step: 'Notify', desc: 'Landlord notified with report; applicant receives status update' },
    ],
    results: [{ big: '20m', label: 'Processing time' }, { big: '100%', label: 'Consistent criteria' }, { big: '+3x', label: 'Applications handled' }],
    techStack: ['n8n', 'DocuSign', 'Stripe', 'HubSpot', 'Node.js'],
    related: ['ai-lead-response', 'property-listing-sync', 'client-onboarding-pipeline'],
  },
  {
    slug: 'booking-confirmation-flow',
    title: 'Booking Confirmation Flow',
    industry: 'Travel',
    color: '#00ff9d',
    stat: '100%',
    desc: 'Instant multi-channel booking confirmation with upsell sequences and pre-arrival comms.',
    problem: 'Guests received slow, generic confirmation emails. No follow-up for upsells or pre-arrival information. Staff were manually sending the same information hundreds of times per week.',
    howItWorks: [
      { step: 'Trigger', desc: 'Booking confirmed in PMS (Opera, Mews, or equivalent)' },
      { step: 'Process', desc: 'Guest profile enriched; upsell eligibility checked; templates personalised' },
      { step: 'Output', desc: 'Instant confirmation email + WhatsApp + upsell sequence scheduled' },
      { step: 'Notify', desc: 'Pre-arrival messages sent at 7 days, 3 days, and day-of automatically' },
    ],
    results: [{ big: '100%', label: 'Instant confirmation' }, { big: '+22%', label: 'Upsell revenue' }, { big: '0', label: 'Manual follow-ups' }],
    techStack: ['n8n', 'WhatsApp API', 'Mews PMS', 'Stripe', 'Mailchimp'],
    related: ['guest-review-response', 'kpi-dashboard-report', 'client-onboarding-pipeline'],
  },
  {
    slug: 'supplier-quote-aggregator',
    title: 'Supplier Quote Aggregator',
    industry: 'Manufacturing',
    color: '#f9ca00',
    stat: '3d→4h',
    desc: 'Automated RFQ distribution, response collection, and comparison matrix generation.',
    problem: 'Procurement teams emailed the same RFQ to 10–20 suppliers, then manually chased responses and built comparison spreadsheets — a process that took 3+ days per procurement cycle.',
    howItWorks: [
      { step: 'Trigger', desc: 'RFQ created in procurement system or spreadsheet' },
      { step: 'Process', desc: 'Quotes distributed to approved supplier list via email with tracking' },
      { step: 'Output', desc: 'Responses parsed and comparison matrix built automatically' },
      { step: 'Notify', desc: 'Procurement manager receives ranked comparison with best-value recommendation' },
    ],
    results: [{ big: '4h', label: 'RFQ cycle time' }, { big: '3x', label: 'Supplier coverage' }, { big: '-60%', label: 'Procurement cost' }],
    techStack: ['n8n', 'Gmail API', 'Google Sheets', 'GPT-4o', 'Slack'],
    related: ['marketplace-price-sync', 'invoice-document-ai', 'revenue-leakage-detector'],
  },
  {
    slug: 'hr-onboarding-bot',
    title: 'HR Onboarding Bot',
    industry: 'HR / People Ops',
    color: '#00c8ff',
    stat: '2d→2h',
    desc: 'Complete new hire onboarding: accounts, documents, intro schedule — all automated.',
    problem: 'HR teams spent 2 days per new hire creating accounts, sending forms, collecting documents, and scheduling intro meetings — all done manually across disconnected tools.',
    howItWorks: [
      { step: 'Trigger', desc: 'Offer letter signed or new hire added to HRIS' },
      { step: 'Process', desc: 'Creates all accounts, sends onboarding forms, builds 30-day schedule' },
      { step: 'Output', desc: 'Welcome pack with all credentials and first-week calendar sent to new hire' },
      { step: 'Notify', desc: 'Manager and IT notified with completion checklist; buddy assigned automatically' },
    ],
    results: [{ big: '2h', label: 'Onboarding time' }, { big: '0', label: 'HR manual steps' }, { big: '+40%', label: 'New hire satisfaction' }],
    techStack: ['n8n', 'BambooHR', 'Slack', 'Google Workspace', 'DocuSign'],
    related: ['client-onboarding-pipeline', 'contract-renewal-alerts', 'kpi-dashboard-report'],
  },
  {
    slug: 'social-media-pipeline',
    title: 'Social Media Content Pipeline',
    industry: 'Marketing',
    color: '#b06eff',
    stat: '10h→0',
    desc: 'AI-generated social content approved and scheduled — no more weekly content marathons.',
    problem: 'Marketing teams were spending 10+ hours weekly writing captions, resizing images, and manually scheduling posts across Instagram, LinkedIn, and Twitter/X.',
    howItWorks: [
      { step: 'Trigger', desc: 'Content calendar event or manual trigger for content batch' },
      { step: 'Process', desc: 'AI generates captions in brand voice, pulls images from asset library' },
      { step: 'Output', desc: 'Content draft sent for one-click approval before scheduling' },
      { step: 'Notify', desc: 'Approved content scheduled across all platforms; performance tracked' },
    ],
    results: [{ big: '0h', label: 'Manual content time' }, { big: '+3x', label: 'Posting frequency' }, { big: '+18%', label: 'Engagement rate' }],
    techStack: ['GPT-4o', 'n8n', 'Buffer API', 'Canva API', 'Google Drive'],
    related: ['kpi-dashboard-report', 'client-onboarding-pipeline', 'guest-review-response'],
  },
  {
    slug: 'contract-renewal-alerts',
    title: 'Contract Renewal Alerts',
    industry: 'Legal / SaaS',
    color: '#00ff9d',
    stat: '0 missed',
    desc: 'Automated contract tracking with tiered renewal alerts — no contract ever expires by accident.',
    problem: 'Companies were missing contract renewal windows, losing favourable terms or auto-renewing contracts they wanted to exit. Contracts were tracked in spreadsheets that no one maintained.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled scan of contract database + calendar check' },
      { step: 'Process', desc: 'Identifies renewals due in 90, 60, 30, and 14 days' },
      { step: 'Output', desc: 'Tiered alerts with contract summary, renewal options, and contact details' },
      { step: 'Notify', desc: 'Decision-maker receives action checklist with one-click renewal or exit options' },
    ],
    results: [{ big: '0', label: 'Missed renewals' }, { big: '90d', label: 'Advance warning' }, { big: '100%', label: 'Contract visibility' }],
    techStack: ['n8n', 'Notion API', 'Slack', 'DocuSign', 'Google Calendar'],
    related: ['invoice-document-ai', 'regulatory-compliance-monitor', 'client-onboarding-pipeline'],
  },
  {
    slug: 'crop-monitoring-alert',
    title: 'Crop Monitoring & Alert',
    industry: 'Agriculture',
    color: '#f9ca00',
    stat: '-40%',
    desc: 'Sensor-driven crop monitoring with AI anomaly detection — catch problems before they cost you.',
    problem: 'Farmers relied on daily physical inspection to detect irrigation failures, pest outbreaks, or nutrient deficiencies. Problems were often discovered too late, causing significant crop loss.',
    howItWorks: [
      { step: 'Trigger', desc: 'IoT sensors read soil moisture, pH, temperature, and humidity every 15 min' },
      { step: 'Process', desc: 'AI baseline model detects anomalies and predicts risk level' },
      { step: 'Output', desc: 'Field-specific alert sent to farm manager with diagnosis and recommended action' },
      { step: 'Notify', desc: 'Incident logged; weekly summary report generated automatically' },
    ],
    results: [{ big: '-40%', label: 'Crop loss' }, { big: '15min', label: 'Detection window' }, { big: '+28%', label: 'Yield improvement' }],
    techStack: ['MQTT', 'InfluxDB', 'Python', 'n8n', 'WhatsApp API'],
    related: ['iot-alert-escalation', 'kpi-dashboard-report', 'supplier-quote-aggregator'],
  },
  {
    slug: 'support-ticket-triage',
    title: 'Support Ticket Triage AI',
    industry: 'SaaS / Tech',
    color: '#00c8ff',
    stat: '4min→30s',
    desc: 'AI ticket classification, routing, and response drafting — first response in 30 seconds.',
    problem: 'Support teams were manually reading, categorising, and routing every ticket, then drafting first responses from scratch. High-priority bugs were buried under billing questions.',
    howItWorks: [
      { step: 'Trigger', desc: 'New support ticket created via email, Intercom, or Zendesk' },
      { step: 'Process', desc: 'AI classifies type, severity, and product area; checks knowledge base' },
      { step: 'Output', desc: 'Auto-draft response sent for urgent/simple tickets; complex tickets routed with context' },
      { step: 'Notify', desc: 'P1 bugs escalated to engineering Slack immediately with full context' },
    ],
    results: [{ big: '30s', label: 'First response' }, { big: '65%', label: 'Auto-resolved' }, { big: '+48%', label: 'CSAT score' }],
    techStack: ['GPT-4o', 'n8n', 'Zendesk API', 'Slack', 'Linear'],
    related: ['hr-onboarding-bot', 'client-onboarding-pipeline', 'kpi-dashboard-report'],
  },
  {
    slug: 'revenue-leakage-detector',
    title: 'Revenue Leakage Detector',
    industry: 'Finance',
    color: '#b06eff',
    stat: 'AED 18K',
    desc: 'Automated revenue reconciliation that finds missed charges, unbilled work, and billing errors.',
    problem: 'Professional services firms and SaaS companies were losing 5–15% of revenue to unbilled work, missed renewals, and billing errors that went undetected until year-end audits.',
    howItWorks: [
      { step: 'Trigger', desc: 'Weekly scheduled run + real-time trigger on invoice creation' },
      { step: 'Process', desc: 'Reconciles time tracking, contracts, and invoices to find discrepancies' },
      { step: 'Output', desc: 'Leakage report with itemised missed charges and correction recommendations' },
      { step: 'Notify', desc: 'Finance manager receives weekly recovery summary with action items' },
    ],
    results: [{ big: 'AED 18K', label: 'Recovered/month' }, { big: '0', label: 'Missed billing cycles' }, { big: '+9%', label: 'Revenue recovery' }],
    techStack: ['Python', 'n8n', 'Xero API', 'Google Sheets', 'Slack'],
    related: ['invoice-document-ai', 'kpi-dashboard-report', 'contract-renewal-alerts'],
  },
  {
    slug: 'regulatory-compliance-monitor',
    title: 'Regulatory Compliance Monitor',
    industry: 'Finance / Legal',
    color: '#00ff9d',
    stat: '100%',
    desc: 'Automated compliance monitoring across licences, filings, and regulatory deadlines.',
    problem: 'Compliance teams were managing dozens of licence renewals, filing deadlines, and regulatory changes across spreadsheets and email reminders — missing deadlines and facing penalties.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled daily scan of compliance calendar and regulatory feeds' },
      { step: 'Process', desc: 'Checks status of all active licences and required filings against deadlines' },
      { step: 'Output', desc: 'Dashboard updated; tiered alerts sent for overdue and approaching items' },
      { step: 'Notify', desc: 'Compliance officer receives daily digest; board notified of critical items' },
    ],
    results: [{ big: '100%', label: 'Deadline coverage' }, { big: '0', label: 'Compliance penalties' }, { big: '90d', label: 'Advance alerts' }],
    techStack: ['n8n', 'Notion', 'Slack', 'Google Calendar', 'Python'],
    related: ['contract-renewal-alerts', 'invoice-document-ai', 'kpi-dashboard-report'],
  },
  {
    slug: 'property-listing-sync',
    title: 'Property Listing Sync',
    industry: 'Real Estate',
    color: '#f9ca00',
    stat: '99%',
    desc: 'One update syncs to all portals instantly — Bayut, PropertyFinder, Dubizzle, and your website.',
    problem: 'Property managers were manually updating listings on 4–6 portals, leading to price inconsistencies, wrong availability, and hours of copy-pasting work every day.',
    howItWorks: [
      { step: 'Trigger', desc: 'Property update in master database or agent CRM' },
      { step: 'Process', desc: 'Formats listing per portal spec; handles image resizing and field mapping' },
      { step: 'Output', desc: 'All portals updated within 5 minutes of the change' },
      { step: 'Notify', desc: 'Sync report generated; failed updates flagged with retry logic' },
    ],
    results: [{ big: '99%', label: 'Sync success rate' }, { big: '5min', label: 'Update latency' }, { big: '-4h', label: 'Daily manual work' }],
    techStack: ['n8n', 'Bayut API', 'PropertyFinder API', 'Node.js', 'PostgreSQL'],
    related: ['ai-lead-response', 'tenant-screening', 'marketplace-price-sync'],
  },
  {
    slug: 'guest-review-response',
    title: 'Guest Review Response AI',
    industry: 'Hospitality',
    color: '#00c8ff',
    stat: '<2h',
    desc: 'AI-generated review responses for every platform — personalised, on-brand, and instant.',
    problem: 'Hotel and short-term rental managers were spending 30–60 minutes daily responding to Google, TripAdvisor, and Booking.com reviews. Negative reviews were going unanswered for days.',
    howItWorks: [
      { step: 'Trigger', desc: 'New review detected on Google, TripAdvisor, Booking.com, or Airbnb' },
      { step: 'Process', desc: 'AI analyses sentiment, extracts key points, generates personalised response' },
      { step: 'Output', desc: 'Draft response posted or sent for one-click approval within 2 hours' },
      { step: 'Notify', desc: 'Negative reviews escalated to manager; sentiment trends reported weekly' },
    ],
    results: [{ big: '<2h', label: 'Response time' }, { big: '100%', label: 'Review coverage' }, { big: '+0.4★', label: 'Rating improvement' }],
    techStack: ['GPT-4o', 'n8n', 'Google My Business API', 'Booking.com API', 'Slack'],
    related: ['booking-confirmation-flow', 'social-media-pipeline', 'support-ticket-triage'],
  },
];
