/* eslint-disable */
export interface FlowStep {
  id: string;
  label: string;
  sublabel?: string;
  type: 'trigger' | 'process' | 'parallel' | 'output' | 'result';
}

export interface Automation {
  slug: string;
  title: string;
  platform: 'n8n' | 'Make.com' | 'Zapier' | 'UiPath';
  industry: string;
  color: string;
  stat: string;
  desc: string;
  problem: string;
  howItWorks: { step: string; desc: string }[];
  results: { big: string; label: string }[];
  techStack: string[];
  related: string[];
  flowSteps: FlowStep[];
}

export const AUTOMATIONS: Automation[] = [
  // ─────────────────────────────────────────────────────────────
  // n8n AUTOMATIONS (18)
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'ai-lead-response',
    title: 'AI Lead Response',
    platform: 'n8n',
    industry: 'Real Estate',
    color: '#f9ca00',
    stat: '90s',
    desc: 'Instant AI-powered lead qualification and WhatsApp response for every inbound enquiry.',
    problem: 'Sales teams were losing leads to competitors who responded faster. Manual response times averaged 4+ hours, and agents spent most of their day copy-pasting templates and updating CRM records.',
    howItWorks: [
      { step: 'Trigger', desc: 'New lead arrives via web form, WhatsApp, Bayut, or PropertyFinder' },
      { step: 'Process', desc: 'GPT-4o reads intent, budget, timeline and scores the lead 1–100' },
      { step: 'Output', desc: 'Personalised WhatsApp + email sent in the lead\'s language within 90 seconds' },
      { step: 'Notify', desc: 'Best-match agent notified with full lead context and score in HubSpot' },
    ],
    results: [{ big: '90s', label: 'Avg response time' }, { big: '94%', label: 'Auto-handled' }, { big: '+38%', label: 'Qualified leads/mo' }],
    techStack: ['GPT-4o', 'WhatsApp Business API', 'n8n', 'HubSpot', 'Node.js'],
    related: ['tenant-screening', 'property-listing-sync', 'booking-confirmation-flow'],
    flowSteps: [
      { id: 'trigger', label: 'PropertyFinder', sublabel: 'Lead form submitted', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'GPT-4o scores lead', type: 'process' },
      { id: 'output', label: 'WhatsApp + Email', sublabel: 'Personalised reply', type: 'output' },
      { id: 'notify', label: 'HubSpot', sublabel: 'Agent notified', type: 'output' },
      { id: 'result', label: '90s', sublabel: 'Zero manual steps', type: 'result' },
    ],
  },
  {
    slug: 'invoice-document-ai',
    title: 'Invoice & Document AI',
    platform: 'n8n',
    industry: 'Finance',
    color: '#00c8ff',
    stat: '98%',
    desc: 'Automated invoice extraction, validation, and approval routing — zero manual data entry.',
    problem: 'Finance teams were manually keying invoice data from PDFs into accounting systems, taking 15–20 minutes per invoice and introducing frequent errors. Approval chains were tracked by email.',
    howItWorks: [
      { step: 'Trigger', desc: 'Invoice PDF arrives via email or upload portal' },
      { step: 'Process', desc: 'AI extracts vendor, amounts, line items, VAT with 98%+ accuracy' },
      { step: 'Output', desc: 'Structured data pushed to accounting system with validation flags' },
      { step: 'Notify', desc: 'Approver notified via Slack/email with one-click approve/reject' },
    ],
    results: [{ big: '98%', label: 'Extraction accuracy' }, { big: '15min→45s', label: 'Per invoice' }, { big: '0', label: 'Manual data entry' }],
    techStack: ['GPT-4o Vision', 'Python', 'n8n', 'QuickBooks API', 'Slack'],
    related: ['contract-renewal-alerts', 'regulatory-compliance-monitor', 'revenue-leakage-detector'],
    flowSteps: [
      { id: 'trigger', label: 'Email / Portal', sublabel: 'PDF arrives', type: 'trigger' },
      { id: 'process', label: 'n8n + GPT-4o', sublabel: 'Extracts line items', type: 'process' },
      { id: 'output', label: 'QuickBooks', sublabel: 'Data pushed', type: 'output' },
      { id: 'notify', label: 'Slack', sublabel: 'One-click approval', type: 'output' },
      { id: 'result', label: '45s', sublabel: '98% accuracy', type: 'result' },
    ],
  },
  {
    slug: 'kpi-dashboard-report',
    title: 'KPI Dashboard Auto-Report',
    platform: 'n8n',
    industry: 'Professional Services',
    color: '#b06eff',
    stat: '6h→0',
    desc: 'Automated weekly KPI reports delivered to your inbox — no spreadsheet assembly required.',
    problem: 'Management teams spent 6+ hours every Monday pulling data from multiple systems, formatting it into slides, and emailing reports. The data was often stale by the time it was sent.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled every Monday 7am (or custom frequency)' },
      { step: 'Process', desc: 'Pulls live data from CRM, ad platforms, analytics, and finance systems' },
      { step: 'Output', desc: 'Generates branded PDF/HTML report with charts and commentary' },
      { step: 'Notify', desc: 'Delivered to email list and posted to Slack channel automatically' },
    ],
    results: [{ big: '0h', label: 'Manual report time' }, { big: '7am', label: 'Monday delivery' }, { big: '100%', label: 'Data freshness' }],
    techStack: ['n8n', 'Google Sheets API', 'HubSpot', 'Slack', 'Puppeteer'],
    related: ['revenue-leakage-detector', 'ai-lead-response', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduler', sublabel: 'Every Monday 7am', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Pulls CRM + analytics', type: 'process' },
      { id: 'output', label: 'Puppeteer', sublabel: 'PDF report generated', type: 'output' },
      { id: 'notify', label: 'Email + Slack', sublabel: 'Auto-delivered', type: 'output' },
      { id: 'result', label: '0h', sublabel: 'Manual effort', type: 'result' },
    ],
  },
  {
    slug: 'client-onboarding-pipeline',
    title: 'Client Onboarding Pipeline',
    platform: 'n8n',
    industry: 'Professional Services',
    color: '#00ff9d',
    stat: '2d→15m',
    desc: 'Fully automated client onboarding from contract signature to first meeting in 15 minutes.',
    problem: 'New client setup took 2 days of manual work: creating accounts, sending welcome documents, scheduling meetings, setting up project tools, and updating the CRM — all done by hand.',
    howItWorks: [
      { step: 'Trigger', desc: 'Contract signed via DocuSign or equivalent' },
      { step: 'Process', desc: 'Creates client folder, sets up project board, generates credentials' },
      { step: 'Output', desc: 'Welcome email with documents and meeting link sent automatically' },
      { step: 'Notify', desc: 'Team notified with client brief and kickoff meeting added to calendar' },
    ],
    results: [{ big: '15m', label: 'Onboarding time' }, { big: '0', label: 'Manual steps' }, { big: '+28%', label: 'Client satisfaction' }],
    techStack: ['n8n', 'DocuSign', 'HubSpot', 'Notion API', 'Google Calendar'],
    related: ['kpi-dashboard-report', 'contract-renewal-alerts', 'hr-onboarding-bot'],
    flowSteps: [
      { id: 'trigger', label: 'DocuSign', sublabel: 'Contract signed', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Orchestrates setup', type: 'process' },
      { id: 'output', label: 'Notion + Calendar', sublabel: 'Workspace created', type: 'output' },
      { id: 'notify', label: 'HubSpot', sublabel: 'CRM updated', type: 'output' },
      { id: 'result', label: '15min', sublabel: 'Full onboarding', type: 'result' },
    ],
  },
  {
    slug: 'iot-alert-escalation',
    title: 'IoT Alert & Escalation',
    platform: 'n8n',
    industry: 'Agriculture',
    color: '#f9ca00',
    stat: '3 prevented',
    desc: 'Real-time IoT sensor monitoring with intelligent alert escalation — zero missed critical events.',
    problem: 'Equipment failures and out-of-range sensor readings were going unnoticed for hours, causing crop losses and production downtime. Alert emails were lost in overflowing inboxes.',
    howItWorks: [
      { step: 'Trigger', desc: 'Sensor reading exceeds threshold or connection lost' },
      { step: 'Process', desc: 'AI classifies severity, checks history, and decides escalation level' },
      { step: 'Output', desc: 'Tiered alerts: Slack for minor, WhatsApp for major, phone call for critical' },
      { step: 'Notify', desc: 'Incident logged automatically with timestamp, sensor ID, and reading' },
    ],
    results: [{ big: '3', label: 'Failures prevented' }, { big: '<30s', label: 'Alert latency' }, { big: '0', label: 'Missed critical events' }],
    techStack: ['MQTT', 'Node.js', 'n8n', 'WhatsApp API', 'PostgreSQL'],
    related: ['crop-monitoring-alert', 'support-ticket-triage', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'MQTT Sensor', sublabel: 'Threshold exceeded', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'AI severity check', type: 'process' },
      { id: 'output', label: 'WhatsApp / Slack', sublabel: 'Tiered alert sent', type: 'output' },
      { id: 'log', label: 'PostgreSQL', sublabel: 'Incident logged', type: 'output' },
      { id: 'result', label: '<30s', sublabel: 'Zero missed events', type: 'result' },
    ],
  },
  {
    slug: 'marketplace-price-sync',
    title: 'Marketplace Price Sync',
    platform: 'n8n',
    industry: 'E-commerce',
    color: '#00c8ff',
    stat: '99.9%',
    desc: 'Real-time price synchronisation across all marketplaces — no more manual listing updates.',
    problem: 'Teams were spending hours daily updating prices and stock levels across Amazon, Noon, and the own website. Price discrepancies were causing order cancellations and customer complaints.',
    howItWorks: [
      { step: 'Trigger', desc: 'Price or stock change detected in master catalogue or ERP' },
      { step: 'Process', desc: 'Maps product IDs across platforms and formats per marketplace spec' },
      { step: 'Output', desc: 'Updates pushed to all active channels within 60 seconds' },
      { step: 'Notify', desc: 'Sync report generated daily with error flagging for failed updates' },
    ],
    results: [{ big: '99.9%', label: 'Sync accuracy' }, { big: '60s', label: 'Update latency' }, { big: '-82%', label: 'Price error rate' }],
    techStack: ['n8n', 'Amazon SP-API', 'Shopify API', 'Node.js', 'PostgreSQL'],
    related: ['supplier-quote-aggregator', 'ai-lead-response', 'revenue-leakage-detector'],
    flowSteps: [
      { id: 'trigger', label: 'ERP / Catalogue', sublabel: 'Price changed', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'ID mapping + format', type: 'process' },
      { id: 'output', label: 'Amazon + Shopify', sublabel: 'All channels updated', type: 'output' },
      { id: 'result', label: '60s', sublabel: '99.9% accuracy', type: 'result' },
    ],
  },
  {
    slug: 'tenant-screening',
    title: 'Tenant Screening Automation',
    platform: 'n8n',
    industry: 'Real Estate',
    color: '#b06eff',
    stat: '4h→20m',
    desc: 'Automated tenant application processing, document verification, and score reporting.',
    problem: 'Property managers spent 4+ hours per application collecting documents, running checks, and compiling reports. Inconsistent screening criteria led to compliance risks.',
    howItWorks: [
      { step: 'Trigger', desc: 'Tenant application submitted via online form' },
      { step: 'Process', desc: 'Documents collected, identity verified, credit/employment checks run' },
      { step: 'Output', desc: 'Standardised screening report with pass/review/decline recommendation' },
      { step: 'Notify', desc: 'Landlord notified with report; applicant receives status update' },
    ],
    results: [{ big: '20m', label: 'Processing time' }, { big: '100%', label: 'Consistent criteria' }, { big: '+3x', label: 'Applications handled' }],
    techStack: ['n8n', 'DocuSign', 'Stripe', 'HubSpot', 'Node.js'],
    related: ['ai-lead-response', 'property-listing-sync', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Online Form', sublabel: 'Application submitted', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'ID + credit checks', type: 'process' },
      { id: 'output', label: 'Screening Report', sublabel: 'Pass/review/decline', type: 'output' },
      { id: 'notify', label: 'Email', sublabel: 'Landlord + applicant', type: 'output' },
      { id: 'result', label: '20min', sublabel: 'vs 4h manual', type: 'result' },
    ],
  },
  {
    slug: 'booking-confirmation-flow',
    title: 'Booking Confirmation Flow',
    platform: 'n8n',
    industry: 'Travel',
    color: '#00ff9d',
    stat: '100%',
    desc: 'Instant multi-channel booking confirmation with upsell sequences and pre-arrival comms.',
    problem: 'Guests received slow, generic confirmation emails. No follow-up for upsells or pre-arrival information. Staff were manually sending the same information hundreds of times per week.',
    howItWorks: [
      { step: 'Trigger', desc: 'Booking confirmed in PMS (Opera, Mews, or equivalent)' },
      { step: 'Process', desc: 'Guest profile enriched; upsell eligibility checked; templates personalised' },
      { step: 'Output', desc: 'Instant confirmation email + WhatsApp + upsell sequence scheduled' },
      { step: 'Notify', desc: 'Pre-arrival messages sent at 7 days, 3 days, and day-of automatically' },
    ],
    results: [{ big: '100%', label: 'Instant confirmation' }, { big: '+22%', label: 'Upsell revenue' }, { big: '0', label: 'Manual follow-ups' }],
    techStack: ['n8n', 'WhatsApp API', 'Mews PMS', 'Stripe', 'Mailchimp'],
    related: ['guest-review-response', 'kpi-dashboard-report', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Mews PMS', sublabel: 'Booking confirmed', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Profile enrichment', type: 'process' },
      { id: 'output', label: 'Email + WhatsApp', sublabel: 'Instant confirmation', type: 'output' },
      { id: 'upsell', label: 'Upsell Sequence', sublabel: 'Scheduled drip', type: 'output' },
      { id: 'result', label: '+22%', sublabel: 'Upsell revenue', type: 'result' },
    ],
  },
  {
    slug: 'supplier-quote-aggregator',
    title: 'Supplier Quote Aggregator',
    platform: 'n8n',
    industry: 'Manufacturing',
    color: '#f9ca00',
    stat: '3d→4h',
    desc: 'Automated RFQ distribution, response collection, and comparison matrix generation.',
    problem: 'Procurement teams emailed the same RFQ to 10–20 suppliers, then manually chased responses and built comparison spreadsheets — a process that took 3+ days per procurement cycle.',
    howItWorks: [
      { step: 'Trigger', desc: 'RFQ created in procurement system or spreadsheet' },
      { step: 'Process', desc: 'Quotes distributed to approved supplier list via email with tracking' },
      { step: 'Output', desc: 'Responses parsed and comparison matrix built automatically' },
      { step: 'Notify', desc: 'Procurement manager receives ranked comparison with best-value recommendation' },
    ],
    results: [{ big: '4h', label: 'RFQ cycle time' }, { big: '3x', label: 'Supplier coverage' }, { big: '-60%', label: 'Procurement cost' }],
    techStack: ['n8n', 'Gmail API', 'Google Sheets', 'GPT-4o', 'Slack'],
    related: ['marketplace-price-sync', 'invoice-document-ai', 'revenue-leakage-detector'],
    flowSteps: [
      { id: 'trigger', label: 'Procurement System', sublabel: 'RFQ created', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Distributes RFQ', type: 'process' },
      { id: 'output', label: 'Gmail', sublabel: 'Suppliers emailed', type: 'output' },
      { id: 'matrix', label: 'Google Sheets', sublabel: 'Comparison built', type: 'output' },
      { id: 'result', label: '4h', sublabel: 'vs 3 days', type: 'result' },
    ],
  },
  {
    slug: 'hr-onboarding-bot',
    title: 'HR Onboarding Bot',
    platform: 'n8n',
    industry: 'HR',
    color: '#00c8ff',
    stat: '2d→2h',
    desc: 'Complete new hire onboarding: accounts, documents, intro schedule — all automated.',
    problem: 'HR teams spent 2 days per new hire creating accounts, sending forms, collecting documents, and scheduling intro meetings — all done manually across disconnected tools.',
    howItWorks: [
      { step: 'Trigger', desc: 'Offer letter signed or new hire added to HRIS' },
      { step: 'Process', desc: 'Creates all accounts, sends onboarding forms, builds 30-day schedule' },
      { step: 'Output', desc: 'Welcome pack with all credentials and first-week calendar sent to new hire' },
      { step: 'Notify', desc: 'Manager and IT notified with completion checklist; buddy assigned automatically' },
    ],
    results: [{ big: '2h', label: 'Onboarding time' }, { big: '0', label: 'HR manual steps' }, { big: '+40%', label: 'New hire satisfaction' }],
    techStack: ['n8n', 'BambooHR', 'Slack', 'Google Workspace', 'DocuSign'],
    related: ['client-onboarding-pipeline', 'contract-renewal-alerts', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'BambooHR', sublabel: 'Offer signed', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Account creation', type: 'process' },
      { id: 'output', label: 'Google Workspace', sublabel: 'Credentials sent', type: 'output' },
      { id: 'notify', label: 'Slack', sublabel: 'Manager + IT alerted', type: 'output' },
      { id: 'result', label: '2h', sublabel: 'Full onboarding', type: 'result' },
    ],
  },
  {
    slug: 'social-media-pipeline',
    title: 'Social Media Content Pipeline',
    platform: 'n8n',
    industry: 'Professional Services',
    color: '#b06eff',
    stat: '10h→0',
    desc: 'AI-generated social content approved and scheduled — no more weekly content marathons.',
    problem: 'Marketing teams were spending 10+ hours weekly writing captions, resizing images, and manually scheduling posts across Instagram, LinkedIn, and Twitter/X.',
    howItWorks: [
      { step: 'Trigger', desc: 'Content calendar event or manual trigger for content batch' },
      { step: 'Process', desc: 'AI generates captions in brand voice, pulls images from asset library' },
      { step: 'Output', desc: 'Content draft sent for one-click approval before scheduling' },
      { step: 'Notify', desc: 'Approved content scheduled across all platforms; performance tracked' },
    ],
    results: [{ big: '0h', label: 'Manual content time' }, { big: '+3x', label: 'Posting frequency' }, { big: '+18%', label: 'Engagement rate' }],
    techStack: ['GPT-4o', 'n8n', 'Buffer API', 'Canva API', 'Google Drive'],
    related: ['kpi-dashboard-report', 'client-onboarding-pipeline', 'guest-review-response'],
    flowSteps: [
      { id: 'trigger', label: 'Content Calendar', sublabel: 'Post scheduled', type: 'trigger' },
      { id: 'process', label: 'n8n + GPT-4o', sublabel: 'Captions generated', type: 'process' },
      { id: 'output', label: 'Approval Email', sublabel: 'One-click review', type: 'output' },
      { id: 'schedule', label: 'Buffer', sublabel: 'Auto-scheduled', type: 'output' },
      { id: 'result', label: '+18%', sublabel: 'Engagement rate', type: 'result' },
    ],
  },
  {
    slug: 'contract-renewal-alerts',
    title: 'Contract Renewal Alerts',
    platform: 'n8n',
    industry: 'Legal',
    color: '#00ff9d',
    stat: '0 missed',
    desc: 'Automated contract tracking with tiered renewal alerts — no contract ever expires by accident.',
    problem: 'Companies were missing contract renewal windows, losing favourable terms or auto-renewing contracts they wanted to exit. Contracts were tracked in spreadsheets that no one maintained.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled scan of contract database + calendar check' },
      { step: 'Process', desc: 'Identifies renewals due in 90, 60, 30, and 14 days' },
      { step: 'Output', desc: 'Tiered alerts with contract summary, renewal options, and contact details' },
      { step: 'Notify', desc: 'Decision-maker receives action checklist with one-click renewal or exit options' },
    ],
    results: [{ big: '0', label: 'Missed renewals' }, { big: '90d', label: 'Advance warning' }, { big: '100%', label: 'Contract visibility' }],
    techStack: ['n8n', 'Notion API', 'Slack', 'DocuSign', 'Google Calendar'],
    related: ['invoice-document-ai', 'regulatory-compliance-monitor', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduler', sublabel: 'Daily scan', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Checks deadlines', type: 'process' },
      { id: 'output', label: 'Slack + Email', sublabel: 'Tiered alerts', type: 'output' },
      { id: 'action', label: 'DocuSign', sublabel: 'One-click renew', type: 'output' },
      { id: 'result', label: '0', sublabel: 'Missed renewals', type: 'result' },
    ],
  },
  {
    slug: 'crop-monitoring-alert',
    title: 'Crop Monitoring & Alert',
    platform: 'n8n',
    industry: 'Agriculture',
    color: '#f9ca00',
    stat: '-40%',
    desc: 'Sensor-driven crop monitoring with AI anomaly detection — catch problems before they cost you.',
    problem: 'Farmers relied on daily physical inspection to detect irrigation failures, pest outbreaks, or nutrient deficiencies. Problems were often discovered too late, causing significant crop loss.',
    howItWorks: [
      { step: 'Trigger', desc: 'IoT sensors read soil moisture, pH, temperature, and humidity every 15 min' },
      { step: 'Process', desc: 'AI baseline model detects anomalies and predicts risk level' },
      { step: 'Output', desc: 'Field-specific alert sent to farm manager with diagnosis and recommended action' },
      { step: 'Notify', desc: 'Incident logged; weekly summary report generated automatically' },
    ],
    results: [{ big: '-40%', label: 'Crop loss' }, { big: '15min', label: 'Detection window' }, { big: '+28%', label: 'Yield improvement' }],
    techStack: ['MQTT', 'InfluxDB', 'Python', 'n8n', 'WhatsApp API'],
    related: ['iot-alert-escalation', 'kpi-dashboard-report', 'supplier-quote-aggregator'],
    flowSteps: [
      { id: 'trigger', label: 'IoT Sensors', sublabel: 'Every 15 min', type: 'trigger' },
      { id: 'process', label: 'n8n + AI', sublabel: 'Anomaly detection', type: 'process' },
      { id: 'output', label: 'WhatsApp', sublabel: 'Field alert sent', type: 'output' },
      { id: 'log', label: 'InfluxDB', sublabel: 'Logged + tracked', type: 'output' },
      { id: 'result', label: '-40%', sublabel: 'Crop loss', type: 'result' },
    ],
  },
  {
    slug: 'support-ticket-triage',
    title: 'Support Ticket Triage AI',
    platform: 'n8n',
    industry: 'Professional Services',
    color: '#00c8ff',
    stat: '4min→30s',
    desc: 'AI ticket classification, routing, and response drafting — first response in 30 seconds.',
    problem: 'Support teams were manually reading, categorising, and routing every ticket, then drafting first responses from scratch. High-priority bugs were buried under billing questions.',
    howItWorks: [
      { step: 'Trigger', desc: 'New support ticket created via email, Intercom, or Zendesk' },
      { step: 'Process', desc: 'AI classifies type, severity, and product area; checks knowledge base' },
      { step: 'Output', desc: 'Auto-draft response sent for urgent/simple tickets; complex tickets routed with context' },
      { step: 'Notify', desc: 'P1 bugs escalated to engineering Slack immediately with full context' },
    ],
    results: [{ big: '30s', label: 'First response' }, { big: '65%', label: 'Auto-resolved' }, { big: '+48%', label: 'CSAT score' }],
    techStack: ['GPT-4o', 'n8n', 'Zendesk API', 'Slack', 'Linear'],
    related: ['hr-onboarding-bot', 'client-onboarding-pipeline', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'Zendesk', sublabel: 'New ticket', type: 'trigger' },
      { id: 'process', label: 'n8n + GPT-4o', sublabel: 'Classify + draft', type: 'process' },
      { id: 'output', label: 'Auto-reply', sublabel: '65% resolved', type: 'output' },
      { id: 'escalate', label: 'Slack', sublabel: 'P1 escalation', type: 'output' },
      { id: 'result', label: '30s', sublabel: 'First response', type: 'result' },
    ],
  },
  {
    slug: 'revenue-leakage-detector',
    title: 'Revenue Leakage Detector',
    platform: 'n8n',
    industry: 'Finance',
    color: '#b06eff',
    stat: 'AED 18K',
    desc: 'Automated revenue reconciliation that finds missed charges, unbilled work, and billing errors.',
    problem: 'Professional services firms and SaaS companies were losing 5–15% of revenue to unbilled work, missed renewals, and billing errors that went undetected until year-end audits.',
    howItWorks: [
      { step: 'Trigger', desc: 'Weekly scheduled run + real-time trigger on invoice creation' },
      { step: 'Process', desc: 'Reconciles time tracking, contracts, and invoices to find discrepancies' },
      { step: 'Output', desc: 'Leakage report with itemised missed charges and correction recommendations' },
      { step: 'Notify', desc: 'Finance manager receives weekly recovery summary with action items' },
    ],
    results: [{ big: 'AED 18K', label: 'Recovered/month' }, { big: '0', label: 'Missed billing cycles' }, { big: '+9%', label: 'Revenue recovery' }],
    techStack: ['Python', 'n8n', 'Xero API', 'Google Sheets', 'Slack'],
    related: ['invoice-document-ai', 'kpi-dashboard-report', 'contract-renewal-alerts'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduler', sublabel: 'Weekly scan', type: 'trigger' },
      { id: 'process', label: 'n8n + Python', sublabel: 'Reconciliation', type: 'process' },
      { id: 'output', label: 'Xero', sublabel: 'Corrections logged', type: 'output' },
      { id: 'notify', label: 'Slack Report', sublabel: 'Finance alerted', type: 'output' },
      { id: 'result', label: 'AED 18K', sublabel: 'Recovered/month', type: 'result' },
    ],
  },
  {
    slug: 'regulatory-compliance-monitor',
    title: 'Regulatory Compliance Monitor',
    platform: 'n8n',
    industry: 'Legal',
    color: '#00ff9d',
    stat: '100%',
    desc: 'Automated compliance monitoring across licences, filings, and regulatory deadlines.',
    problem: 'Compliance teams were managing dozens of licence renewals, filing deadlines, and regulatory changes across spreadsheets and email reminders — missing deadlines and facing penalties.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled daily scan of compliance calendar and regulatory feeds' },
      { step: 'Process', desc: 'Checks status of all active licences and required filings against deadlines' },
      { step: 'Output', desc: 'Dashboard updated; tiered alerts sent for overdue and approaching items' },
      { step: 'Notify', desc: 'Compliance officer receives daily digest; board notified of critical items' },
    ],
    results: [{ big: '100%', label: 'Deadline coverage' }, { big: '0', label: 'Compliance penalties' }, { big: '90d', label: 'Advance alerts' }],
    techStack: ['n8n', 'Notion', 'Slack', 'Google Calendar', 'Python'],
    related: ['contract-renewal-alerts', 'invoice-document-ai', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduler', sublabel: 'Daily at 8am', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Deadline checks', type: 'process' },
      { id: 'output', label: 'Notion Dashboard', sublabel: 'Status updated', type: 'output' },
      { id: 'notify', label: 'Slack', sublabel: 'Critical items flagged', type: 'output' },
      { id: 'result', label: '100%', sublabel: 'Deadline coverage', type: 'result' },
    ],
  },
  {
    slug: 'property-listing-sync',
    title: 'Property Listing Sync',
    platform: 'n8n',
    industry: 'Real Estate',
    color: '#f9ca00',
    stat: '99%',
    desc: 'One update syncs to all portals instantly — Bayut, PropertyFinder, Dubizzle, and your website.',
    problem: 'Property managers were manually updating listings on 4–6 portals, leading to price inconsistencies, wrong availability, and hours of copy-pasting work every day.',
    howItWorks: [
      { step: 'Trigger', desc: 'Property update in master database or agent CRM' },
      { step: 'Process', desc: 'Formats listing per portal spec; handles image resizing and field mapping' },
      { step: 'Output', desc: 'All portals updated within 5 minutes of the change' },
      { step: 'Notify', desc: 'Sync report generated; failed updates flagged with retry logic' },
    ],
    results: [{ big: '99%', label: 'Sync success rate' }, { big: '5min', label: 'Update latency' }, { big: '-4h', label: 'Daily manual work' }],
    techStack: ['n8n', 'Bayut API', 'PropertyFinder API', 'Node.js', 'PostgreSQL'],
    related: ['ai-lead-response', 'tenant-screening', 'marketplace-price-sync'],
    flowSteps: [
      { id: 'trigger', label: 'Agent CRM', sublabel: 'Listing updated', type: 'trigger' },
      { id: 'process', label: 'n8n', sublabel: 'Format per portal', type: 'process' },
      { id: 'output', label: 'Bayut + PF', sublabel: 'All portals updated', type: 'output' },
      { id: 'report', label: 'Sync Report', sublabel: 'Errors flagged', type: 'output' },
      { id: 'result', label: '5min', sublabel: '99% success rate', type: 'result' },
    ],
  },
  {
    slug: 'guest-review-response',
    title: 'Guest Review Response AI',
    platform: 'n8n',
    industry: 'Travel',
    color: '#00c8ff',
    stat: '<2h',
    desc: 'AI-generated review responses for every platform — personalised, on-brand, and instant.',
    problem: 'Hotel and short-term rental managers were spending 30–60 minutes daily responding to Google, TripAdvisor, and Booking.com reviews. Negative reviews were going unanswered for days.',
    howItWorks: [
      { step: 'Trigger', desc: 'New review detected on Google, TripAdvisor, Booking.com, or Airbnb' },
      { step: 'Process', desc: 'AI analyses sentiment, extracts key points, generates personalised response' },
      { step: 'Output', desc: 'Draft response posted or sent for one-click approval within 2 hours' },
      { step: 'Notify', desc: 'Negative reviews escalated to manager; sentiment trends reported weekly' },
    ],
    results: [{ big: '<2h', label: 'Response time' }, { big: '100%', label: 'Review coverage' }, { big: '+0.4★', label: 'Rating improvement' }],
    techStack: ['GPT-4o', 'n8n', 'Google My Business API', 'Booking.com API', 'Slack'],
    related: ['booking-confirmation-flow', 'social-media-pipeline', 'support-ticket-triage'],
    flowSteps: [
      { id: 'trigger', label: 'Review Platform', sublabel: 'New review detected', type: 'trigger' },
      { id: 'process', label: 'n8n + GPT-4o', sublabel: 'Sentiment + draft', type: 'process' },
      { id: 'output', label: 'Response Posted', sublabel: 'Or approval sent', type: 'output' },
      { id: 'escalate', label: 'Slack', sublabel: 'Negative escalated', type: 'output' },
      { id: 'result', label: '<2h', sublabel: '100% coverage', type: 'result' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Make.com AUTOMATIONS (12)
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'ecommerce-abandoned-cart',
    title: 'Abandoned Cart Recovery',
    platform: 'Make.com',
    industry: 'E-commerce',
    color: '#b06eff',
    stat: '+31%',
    desc: 'Multi-touch abandoned cart recovery via email and SMS — fully automated and personalised.',
    problem: 'E-commerce brands were losing 70%+ of cart value to abandonment with no automated recovery. Manual follow-ups were inconsistent and often sent too late to convert.',
    howItWorks: [
      { step: 'Trigger', desc: 'Cart abandoned for 1 hour detected in Shopify' },
      { step: 'Process', desc: 'Customer profile enriched; discount eligibility checked; sequence personalised' },
      { step: 'Output', desc: '3-touch sequence: email at 1h, SMS at 6h, final email at 24h' },
      { step: 'Notify', desc: 'Recovery analytics tracked; successful recoveries logged to Google Sheets' },
    ],
    results: [{ big: '+31%', label: 'Cart recovery rate' }, { big: '3x', label: 'Touch sequence' }, { big: '-0', label: 'Manual effort' }],
    techStack: ['Make.com', 'Shopify', 'Klaviyo', 'Twilio SMS', 'Google Sheets'],
    related: ['marketplace-price-sync', 'invoice-document-ai', 'social-media-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Shopify', sublabel: 'Cart abandoned 1h', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Personalises sequence', type: 'process' },
      { id: 'email', label: 'Klaviyo', sublabel: 'Email at 1h', type: 'output' },
      { id: 'sms', label: 'Twilio', sublabel: 'SMS at 6h', type: 'output' },
      { id: 'result', label: '+31%', sublabel: 'Recovery rate', type: 'result' },
    ],
  },
  {
    slug: 'healthcare-patient-intake',
    title: 'Patient Intake Automation',
    platform: 'Make.com',
    industry: 'Healthcare',
    color: '#00ff9d',
    stat: '45min→8min',
    desc: 'Digital patient intake: forms, consent, insurance verification — before they walk in the door.',
    problem: 'Clinics were wasting 45 minutes per new patient on paper forms, manual insurance checks, and re-entering data into the EMR. Front desk staff were overwhelmed and error rates were high.',
    howItWorks: [
      { step: 'Trigger', desc: 'Appointment confirmed in scheduling system' },
      { step: 'Process', desc: 'Intake form sent via SMS; insurance verified via API; data mapped to EMR fields' },
      { step: 'Output', desc: 'Patient record created; insurance pre-auth flag raised if needed' },
      { step: 'Notify', desc: 'Clinician receives brief pre-appointment summary; admin alerted to any issues' },
    ],
    results: [{ big: '8min', label: 'Intake time' }, { big: '0', label: 'Manual re-entry' }, { big: '98%', label: 'Form completion' }],
    techStack: ['Make.com', 'Typeform', 'Epic EMR API', 'Twilio', 'Stripe'],
    related: ['hr-onboarding-bot', 'client-onboarding-pipeline', 'support-ticket-triage'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduling System', sublabel: 'Appointment confirmed', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Insurance verify', type: 'process' },
      { id: 'form', label: 'Typeform SMS', sublabel: 'Intake collected', type: 'output' },
      { id: 'emr', label: 'Epic EMR', sublabel: 'Record created', type: 'output' },
      { id: 'result', label: '8min', sublabel: 'vs 45min manual', type: 'result' },
    ],
  },
  {
    slug: 'logistics-shipment-tracking',
    title: 'Shipment Tracking Alerts',
    platform: 'Make.com',
    industry: 'Logistics',
    color: '#f9ca00',
    stat: '-65%',
    desc: 'Proactive shipment status updates across all carriers — customers always know where their order is.',
    problem: 'Logistics teams were fielding hundreds of "where is my order" calls daily. Customers had no visibility after dispatch, and staff were manually checking carrier portals one by one.',
    howItWorks: [
      { step: 'Trigger', desc: 'Shipment status change detected via carrier API polling' },
      { step: 'Process', desc: 'Status normalised across carriers; delay risk scored; customer preference checked' },
      { step: 'Output', desc: 'Proactive update sent via preferred channel (email/SMS/WhatsApp)' },
      { step: 'Notify', desc: 'Delayed shipments escalated to ops; daily exception report generated' },
    ],
    results: [{ big: '-65%', label: 'WISMO calls' }, { big: '100%', label: 'Proactive alerts' }, { big: '+24%', label: 'CSAT increase' }],
    techStack: ['Make.com', 'DHL API', 'FedEx API', 'Twilio', 'Airtable'],
    related: ['marketplace-price-sync', 'supplier-quote-aggregator', 'support-ticket-triage'],
    flowSteps: [
      { id: 'trigger', label: 'Carrier APIs', sublabel: 'Status changed', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Delay risk score', type: 'process' },
      { id: 'output', label: 'SMS / Email', sublabel: 'Customer notified', type: 'output' },
      { id: 'escalate', label: 'Airtable', sublabel: 'Exceptions logged', type: 'output' },
      { id: 'result', label: '-65%', sublabel: 'WISMO calls', type: 'result' },
    ],
  },
  {
    slug: 'finance-expense-approval',
    title: 'Expense Approval Workflow',
    platform: 'Make.com',
    industry: 'Finance',
    color: '#00c8ff',
    stat: '3d→4h',
    desc: 'Automated expense submission, policy check, and multi-level approval routing.',
    problem: 'Employees submitted expense reports by email; finance teams manually checked against policy and chased approvers. Reimbursement took 3+ days and compliance was inconsistently enforced.',
    howItWorks: [
      { step: 'Trigger', desc: 'Expense report submitted via mobile app or web form' },
      { step: 'Process', desc: 'Policy check run automatically; out-of-policy items flagged and noted' },
      { step: 'Output', desc: 'Routed to correct approver based on amount and department; reminder loop active' },
      { step: 'Notify', desc: 'Approved expenses auto-synced to Xero; employee notified of outcome' },
    ],
    results: [{ big: '4h', label: 'Approval time' }, { big: '100%', label: 'Policy compliance' }, { big: '0', label: 'Email chains' }],
    techStack: ['Make.com', 'Google Forms', 'Xero', 'Slack', 'Airtable'],
    related: ['invoice-document-ai', 'revenue-leakage-detector', 'regulatory-compliance-monitor'],
    flowSteps: [
      { id: 'trigger', label: 'Expense Form', sublabel: 'Submitted', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Policy check', type: 'process' },
      { id: 'approval', label: 'Slack', sublabel: 'Routed to approver', type: 'output' },
      { id: 'sync', label: 'Xero', sublabel: 'Auto-synced', type: 'output' },
      { id: 'result', label: '4h', sublabel: 'vs 3 days', type: 'result' },
    ],
  },
  {
    slug: 'real-estate-deal-pipeline',
    title: 'Real Estate Deal Pipeline',
    platform: 'Make.com',
    industry: 'Real Estate',
    color: '#f9ca00',
    stat: '+45%',
    desc: 'Visual deal pipeline automation: stage changes trigger tasks, docs, and agent notifications.',
    problem: 'Real estate brokerages had deals stuck in pipeline stages because follow-up tasks were forgotten and documents were prepared manually. Agents lost track of what needed to happen next.',
    howItWorks: [
      { step: 'Trigger', desc: 'Deal stage changed in Pipedrive or HubSpot CRM' },
      { step: 'Process', desc: 'Stage-specific task list created; required documents identified; deadline set' },
      { step: 'Output', desc: 'Agent receives task checklist; client receives stage-appropriate communication' },
      { step: 'Notify', desc: 'Manager receives pipeline status daily; stalled deals flagged at 72 hours' },
    ],
    results: [{ big: '+45%', label: 'Pipeline velocity' }, { big: '0', label: 'Stalled deals' }, { big: '-30%', label: 'Time per deal' }],
    techStack: ['Make.com', 'Pipedrive', 'DocuSign', 'WhatsApp API', 'Google Drive'],
    related: ['ai-lead-response', 'tenant-screening', 'property-listing-sync'],
    flowSteps: [
      { id: 'trigger', label: 'Pipedrive', sublabel: 'Deal stage changed', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Task list created', type: 'process' },
      { id: 'agent', label: 'WhatsApp', sublabel: 'Agent checklist', type: 'output' },
      { id: 'client', label: 'Email', sublabel: 'Client update', type: 'output' },
      { id: 'result', label: '+45%', sublabel: 'Pipeline velocity', type: 'result' },
    ],
  },
  {
    slug: 'legal-document-automation',
    title: 'Legal Document Generation',
    platform: 'Make.com',
    industry: 'Legal',
    color: '#b06eff',
    stat: '2h→5min',
    desc: 'Automated contract and NDA generation from intake form — legally consistent, instant delivery.',
    problem: 'Law firms and legal ops teams were drafting NDAs, service agreements, and employment contracts manually for each client, taking 1–2 hours per document and introducing version inconsistencies.',
    howItWorks: [
      { step: 'Trigger', desc: 'Client intake form submitted with party names and key terms' },
      { step: 'Process', desc: 'Data merged into pre-approved document template; clause library checked' },
      { step: 'Output', desc: 'Draft document generated and sent via DocuSign for e-signature' },
      { step: 'Notify', desc: 'Lawyer receives copy; CRM updated; executed document stored in matter folder' },
    ],
    results: [{ big: '5min', label: 'Document time' }, { big: '100%', label: 'Template compliance' }, { big: '+60%', label: 'Capacity freed' }],
    techStack: ['Make.com', 'Typeform', 'DocuSign', 'Google Docs API', 'Notion'],
    related: ['contract-renewal-alerts', 'regulatory-compliance-monitor', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Intake Form', sublabel: 'Client details', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Template merge', type: 'process' },
      { id: 'output', label: 'Google Docs', sublabel: 'Draft generated', type: 'output' },
      { id: 'sign', label: 'DocuSign', sublabel: 'E-signature sent', type: 'output' },
      { id: 'result', label: '5min', sublabel: 'vs 2h manual', type: 'result' },
    ],
  },
  {
    slug: 'ecommerce-returns-automation',
    title: 'E-commerce Returns Automation',
    platform: 'Make.com',
    industry: 'E-commerce',
    color: '#00ff9d',
    stat: '-70%',
    desc: 'Self-service return initiation, label generation, and refund processing — no agent needed.',
    problem: 'Customer service teams were handling return requests manually — approving eligibility, generating labels, triggering refunds, and updating inventory. Each return took 12+ minutes of staff time.',
    howItWorks: [
      { step: 'Trigger', desc: 'Customer initiates return via self-service portal or email' },
      { step: 'Process', desc: 'Eligibility checked against order data and return policy automatically' },
      { step: 'Output', desc: 'Return label generated and emailed; Shopify refund triggered on receipt' },
      { step: 'Notify', desc: 'Warehouse alerted for incoming return; inventory updated on confirmation' },
    ],
    results: [{ big: '-70%', label: 'Agent handling time' }, { big: '<5min', label: 'Label delivery' }, { big: '98%', label: 'Policy compliance' }],
    techStack: ['Make.com', 'Shopify', 'EasyPost', 'Stripe', 'Freshdesk'],
    related: ['marketplace-price-sync', 'ecommerce-abandoned-cart', 'logistics-shipment-tracking'],
    flowSteps: [
      { id: 'trigger', label: 'Self-Service Portal', sublabel: 'Return requested', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Eligibility check', type: 'process' },
      { id: 'label', label: 'EasyPost', sublabel: 'Label generated', type: 'output' },
      { id: 'refund', label: 'Stripe', sublabel: 'Refund triggered', type: 'output' },
      { id: 'result', label: '-70%', sublabel: 'Agent time', type: 'result' },
    ],
  },
  {
    slug: 'hr-leave-management',
    title: 'HR Leave Management',
    platform: 'Make.com',
    industry: 'HR',
    color: '#f9ca00',
    stat: '0 emails',
    desc: 'Leave requests, approvals, calendar blocking, and payroll sync — fully automated.',
    problem: 'HR teams processed leave requests via email, manually checking entitlements, approving, updating calendars, and notifying payroll. Each request involved 5–7 manual steps and 2–3 emails.',
    howItWorks: [
      { step: 'Trigger', desc: 'Employee submits leave request via HR portal or Slack command' },
      { step: 'Process', desc: 'Entitlement checked; clash detection run against team calendar' },
      { step: 'Output', desc: 'Manager notified for approval; calendar blocked; payroll system notified on approval' },
      { step: 'Notify', desc: 'Employee receives confirmation; HR dashboard updated in real time' },
    ],
    results: [{ big: '0', label: 'Email chains' }, { big: '24h', label: 'Approval cycle' }, { big: '100%', label: 'Entitlement accuracy' }],
    techStack: ['Make.com', 'BambooHR', 'Google Calendar', 'Slack', 'Xero Payroll'],
    related: ['hr-onboarding-bot', 'client-onboarding-pipeline', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'Slack / Portal', sublabel: 'Leave requested', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Entitlement check', type: 'process' },
      { id: 'approve', label: 'Manager Alert', sublabel: 'Approval flow', type: 'output' },
      { id: 'sync', label: 'Calendar + Payroll', sublabel: 'Auto-updated', type: 'output' },
      { id: 'result', label: '0', sublabel: 'Email chains', type: 'result' },
    ],
  },
  {
    slug: 'manufacturing-quality-alert',
    title: 'Quality Control Alert System',
    platform: 'Make.com',
    industry: 'Manufacturing',
    color: '#00c8ff',
    stat: '-55%',
    desc: 'Real-time quality defect detection and escalation — catch issues before they reach the line end.',
    problem: 'Quality control data was collected on paper sheets and entered into spreadsheets hours later. By the time defects were identified, entire production batches were already affected.',
    howItWorks: [
      { step: 'Trigger', desc: 'QC reading entered via mobile app or scanner on the production floor' },
      { step: 'Process', desc: 'Reading compared against control limits; defect pattern matched against history' },
      { step: 'Output', desc: 'Alert sent to floor supervisor within 60 seconds; line hold flagged if needed' },
      { step: 'Notify', desc: 'Quality manager receives shift summary; repeat defects trigger CAPA workflow' },
    ],
    results: [{ big: '-55%', label: 'Defect escape rate' }, { big: '60s', label: 'Alert latency' }, { big: '+28%', label: 'First-pass yield' }],
    techStack: ['Make.com', 'Airtable', 'Twilio', 'Monday.com', 'Google Sheets'],
    related: ['supplier-quote-aggregator', 'iot-alert-escalation', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'QC Scanner', sublabel: 'Reading submitted', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Limit comparison', type: 'process' },
      { id: 'alert', label: 'Twilio SMS', sublabel: 'Supervisor alerted', type: 'output' },
      { id: 'log', label: 'Monday.com', sublabel: 'CAPA triggered', type: 'output' },
      { id: 'result', label: '-55%', sublabel: 'Defect escapes', type: 'result' },
    ],
  },
  {
    slug: 'travel-itinerary-builder',
    title: 'Travel Itinerary Builder',
    platform: 'Make.com',
    industry: 'Travel',
    color: '#b06eff',
    stat: '4h→20min',
    desc: 'AI-curated travel itineraries built from client brief and sent as branded PDF in 20 minutes.',
    problem: 'Travel consultants spent 3–5 hours per client building custom itineraries from scratch — researching, formatting, and assembling multi-day plans into branded documents.',
    howItWorks: [
      { step: 'Trigger', desc: 'Client brief received via intake form (dates, budget, interests, group size)' },
      { step: 'Process', desc: 'AI curates day-by-day plan; availability checked; pricing pulled from APIs' },
      { step: 'Output', desc: 'Branded PDF itinerary generated and sent to client with booking links' },
      { step: 'Notify', desc: 'Consultant notified with summary; CRM updated; follow-up scheduled in 48 hours' },
    ],
    results: [{ big: '20min', label: 'Itinerary time' }, { big: '+3x', label: 'Client capacity' }, { big: '+27%', label: 'Booking conversion' }],
    techStack: ['Make.com', 'GPT-4o', 'Amadeus API', 'Google Docs', 'HubSpot'],
    related: ['booking-confirmation-flow', 'guest-review-response', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Intake Form', sublabel: 'Client brief', type: 'trigger' },
      { id: 'process', label: 'Make.com + GPT', sublabel: 'AI curation', type: 'process' },
      { id: 'pricing', label: 'Amadeus API', sublabel: 'Live pricing', type: 'output' },
      { id: 'output', label: 'Google Docs PDF', sublabel: 'Sent to client', type: 'output' },
      { id: 'result', label: '20min', sublabel: 'vs 4h manual', type: 'result' },
    ],
  },
  {
    slug: 'saas-trial-conversion',
    title: 'SaaS Trial Conversion Flow',
    platform: 'Make.com',
    industry: 'Professional Services',
    color: '#00ff9d',
    stat: '+38%',
    desc: 'Behaviour-triggered onboarding sequences that convert free trial users to paid customers.',
    problem: 'SaaS companies were sending the same onboarding email to every trial user regardless of their in-app behaviour. Users who never reached the "aha moment" churned without any targeted intervention.',
    howItWorks: [
      { step: 'Trigger', desc: 'User behaviour event fired from product analytics (Mixpanel/Segment)' },
      { step: 'Process', desc: 'Engagement score calculated; risk segment assigned; personalised sequence selected' },
      { step: 'Output', desc: 'Targeted email sequence deployed; at-risk users receive direct sales outreach' },
      { step: 'Notify', desc: 'Sales team alerted for high-intent users; weekly conversion report generated' },
    ],
    results: [{ big: '+38%', label: 'Trial conversion' }, { big: '-40%', label: 'Churn in trial' }, { big: '100%', label: 'Segmented comms' }],
    techStack: ['Make.com', 'Mixpanel', 'Customer.io', 'HubSpot', 'Slack'],
    related: ['support-ticket-triage', 'client-onboarding-pipeline', 'social-media-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Mixpanel', sublabel: 'Behaviour event', type: 'trigger' },
      { id: 'process', label: 'Make.com', sublabel: 'Segment + score', type: 'process' },
      { id: 'email', label: 'Customer.io', sublabel: 'Targeted sequence', type: 'output' },
      { id: 'sales', label: 'HubSpot', sublabel: 'High-intent task', type: 'output' },
      { id: 'result', label: '+38%', sublabel: 'Trial conversion', type: 'result' },
    ],
  },
  {
    slug: 'make-social-listening',
    title: 'Social Listening & Response',
    platform: 'Make.com',
    industry: 'Professional Services',
    color: '#6d2ef1',
    stat: '<30min',
    desc: 'Brand mention monitoring across social platforms with AI-drafted response suggestions.',
    problem: 'Marketing teams were missing brand mentions, competitor activity, and customer complaints posted publicly on Twitter/X, Reddit, and LinkedIn — often discovering them days later.',
    howItWorks: [
      { step: 'Trigger', desc: 'Brand keyword or competitor mention detected via social monitoring API' },
      { step: 'Process', desc: 'Sentiment analysed; urgency scored; competitor mentions filed separately' },
      { step: 'Output', desc: 'Response draft generated and sent to marketing team Slack for approval' },
      { step: 'Notify', desc: 'Weekly sentiment trend report generated; PR crises escalated immediately' },
    ],
    results: [{ big: '<30min', label: 'Response time' }, { big: '100%', label: 'Mention coverage' }, { big: '+15%', label: 'Brand sentiment' }],
    techStack: ['Make.com', 'Brandwatch API', 'GPT-4o', 'Slack', 'Airtable'],
    related: ['social-media-pipeline', 'guest-review-response', 'support-ticket-triage'],
    flowSteps: [
      { id: 'trigger', label: 'Brandwatch', sublabel: 'Mention detected', type: 'trigger' },
      { id: 'process', label: 'Make.com + GPT', sublabel: 'Sentiment + draft', type: 'process' },
      { id: 'output', label: 'Slack', sublabel: 'Team approval', type: 'output' },
      { id: 'report', label: 'Airtable', sublabel: 'Trend tracked', type: 'output' },
      { id: 'result', label: '<30min', sublabel: 'Response time', type: 'result' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // Zapier AUTOMATIONS (10)
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'zapier-crm-lead-routing',
    title: 'CRM Lead Routing & Assignment',
    platform: 'Zapier',
    industry: 'Professional Services',
    color: '#ff4a00',
    stat: '< 2min',
    desc: 'Instant lead scoring and round-robin assignment across sales reps — zero manual routing.',
    problem: 'Inbound leads from web forms and ads were piling up in a shared inbox. Sales managers spent time each day manually assigning leads, often hours after they arrived — losing conversion window.',
    howItWorks: [
      { step: 'Trigger', desc: 'New lead submitted via website form, LinkedIn Lead Gen, or Facebook Ads' },
      { step: 'Process', desc: 'Lead scored by source, company size, and intent signals; territory matched' },
      { step: 'Output', desc: 'Lead created in Salesforce with full context; assigned to correct rep' },
      { step: 'Notify', desc: 'Rep receives Slack and email alert with lead brief and call-back task created' },
    ],
    results: [{ big: '<2min', label: 'Assignment time' }, { big: '+29%', label: 'First-touch conversion' }, { big: '0', label: 'Missed leads' }],
    techStack: ['Zapier', 'Salesforce', 'Facebook Lead Ads', 'Slack', 'HubSpot'],
    related: ['ai-lead-response', 'saas-trial-conversion', 'support-ticket-triage'],
    flowSteps: [
      { id: 'trigger', label: 'Facebook / Form', sublabel: 'Lead submitted', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Score + territory', type: 'process' },
      { id: 'output', label: 'Salesforce', sublabel: 'Lead created', type: 'output' },
      { id: 'notify', label: 'Slack', sublabel: 'Rep alerted', type: 'output' },
      { id: 'result', label: '<2min', sublabel: '+29% conversion', type: 'result' },
    ],
  },
  {
    slug: 'zapier-ecommerce-review-request',
    title: 'Post-Purchase Review Request',
    platform: 'Zapier',
    industry: 'E-commerce',
    color: '#ff4a00',
    stat: '+4.1★',
    desc: 'Timed review request emails sent after confirmed delivery — grow your rating automatically.',
    problem: 'E-commerce stores were getting far fewer reviews than competitors because they relied on customers to leave reviews voluntarily. Only negative experiences drove spontaneous reviews.',
    howItWorks: [
      { step: 'Trigger', desc: 'Shipment marked delivered by carrier integration' },
      { step: 'Process', desc: 'Wait 48 hours; check for returns or complaints before sending' },
      { step: 'Output', desc: 'Personalised review request email sent with product-specific links' },
      { step: 'Notify', desc: 'Review submitted event logged to analytics; low ratings flagged for follow-up' },
    ],
    results: [{ big: '+4.1★', label: 'Avg rating' }, { big: '+220%', label: 'Review volume' }, { big: '0', label: 'Manual outreach' }],
    techStack: ['Zapier', 'Shopify', 'Klaviyo', 'Trustpilot API', 'Google Sheets'],
    related: ['ecommerce-abandoned-cart', 'ecommerce-returns-automation', 'guest-review-response'],
    flowSteps: [
      { id: 'trigger', label: 'Carrier API', sublabel: 'Delivered', type: 'trigger' },
      { id: 'wait', label: 'Zapier', sublabel: 'Wait 48h', type: 'process' },
      { id: 'check', label: 'Return Check', sublabel: 'No complaint', type: 'process' },
      { id: 'output', label: 'Klaviyo', sublabel: 'Review request', type: 'output' },
      { id: 'result', label: '+220%', sublabel: 'Review volume', type: 'result' },
    ],
  },
  {
    slug: 'zapier-job-applicant-screening',
    title: 'Job Applicant Screening Flow',
    platform: 'Zapier',
    industry: 'HR',
    color: '#ff4a00',
    stat: '5h→45min',
    desc: 'Automated applicant tracking: form → ATS → email sequence — from apply to interview invite.',
    problem: 'HR teams were manually reading every CV, logging applications in spreadsheets, and sending individual reply emails. A 50-applicant role consumed 5+ hours of screening time before a single interview.',
    howItWorks: [
      { step: 'Trigger', desc: 'Application submitted via Typeform or LinkedIn apply' },
      { step: 'Process', desc: 'Key fields extracted; knockout question check applied; ATS record created' },
      { step: 'Output', desc: 'Qualified applicants receive interview scheduling link automatically' },
      { step: 'Notify', desc: 'Rejected applicants receive branded decline; HR receives shortlist summary' },
    ],
    results: [{ big: '45min', label: 'Screening time' }, { big: '100%', label: 'Response rate' }, { big: '+2x', label: 'Roles handled/week' }],
    techStack: ['Zapier', 'Typeform', 'Greenhouse ATS', 'Calendly', 'Slack'],
    related: ['hr-onboarding-bot', 'hr-leave-management', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Typeform', sublabel: 'Application in', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Knockout check', type: 'process' },
      { id: 'ats', label: 'Greenhouse', sublabel: 'Record created', type: 'output' },
      { id: 'schedule', label: 'Calendly', sublabel: 'Interview link sent', type: 'output' },
      { id: 'result', label: '45min', sublabel: 'vs 5h manual', type: 'result' },
    ],
  },
  {
    slug: 'zapier-payment-reminder',
    title: 'Invoice Payment Reminder',
    platform: 'Zapier',
    industry: 'Finance',
    color: '#ff4a00',
    stat: '-42%',
    desc: 'Automated overdue invoice reminders with escalating urgency — recover cash faster.',
    problem: 'Finance teams were manually tracking overdue invoices and sending chase emails one by one, often forgetting or sending inconsistent messages. Cash collection cycles were 45+ days.',
    howItWorks: [
      { step: 'Trigger', desc: 'Invoice marked overdue in Xero or QuickBooks' },
      { step: 'Process', desc: 'Days overdue checked; escalation tier selected; contact details fetched' },
      { step: 'Output', desc: 'Tiered reminder emails: friendly at 3d, formal at 7d, escalation at 14d' },
      { step: 'Notify', desc: 'Finance manager alerted at 14d+ overdue; 30d flagged for collections review' },
    ],
    results: [{ big: '-42%', label: 'DSO reduction' }, { big: '3 tiers', label: 'Automated escalation' }, { big: '+33%', label: 'On-time payments' }],
    techStack: ['Zapier', 'Xero', 'Gmail', 'Slack', 'Google Sheets'],
    related: ['invoice-document-ai', 'revenue-leakage-detector', 'finance-expense-approval'],
    flowSteps: [
      { id: 'trigger', label: 'Xero', sublabel: 'Invoice overdue', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Tier selection', type: 'process' },
      { id: 'email', label: 'Gmail', sublabel: 'Reminder sent', type: 'output' },
      { id: 'escalate', label: 'Slack', sublabel: '14d+ alerted', type: 'output' },
      { id: 'result', label: '-42%', sublabel: 'DSO reduction', type: 'result' },
    ],
  },
  {
    slug: 'zapier-news-digest',
    title: 'Industry News Digest',
    platform: 'Zapier',
    industry: 'Professional Services',
    color: '#ff4a00',
    stat: '2h→0',
    desc: 'Automated daily/weekly news digest curated for your industry — delivered to Slack or email.',
    problem: 'Analysts and consultants spent 1–2 hours daily reading industry news across 15+ sources to stay informed. Important developments were missed and team knowledge was uneven.',
    howItWorks: [
      { step: 'Trigger', desc: 'Scheduled run at set time (daily 8am or weekly Monday)' },
      { step: 'Process', desc: 'RSS feeds and news APIs polled; AI summarises and ranks by relevance' },
      { step: 'Output', desc: 'Curated digest compiled and formatted with headlines, summaries, and links' },
      { step: 'Notify', desc: 'Delivered to Slack channel and/or email distribution list' },
    ],
    results: [{ big: '0h', label: 'Manual curation' }, { big: '15+', label: 'Sources covered' }, { big: '100%', label: 'Team coverage' }],
    techStack: ['Zapier', 'RSS Feeds', 'GPT-4o', 'Slack', 'Mailchimp'],
    related: ['kpi-dashboard-report', 'social-media-pipeline', 'make-social-listening'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduler', sublabel: 'Daily 8am', type: 'trigger' },
      { id: 'process', label: 'Zapier + GPT', sublabel: 'Curate + rank', type: 'process' },
      { id: 'output', label: 'Slack', sublabel: 'Digest delivered', type: 'output' },
      { id: 'result', label: '0h', sublabel: 'Manual curation', type: 'result' },
    ],
  },
  {
    slug: 'zapier-healthcare-appointment',
    title: 'Appointment Reminder System',
    platform: 'Zapier',
    industry: 'Healthcare',
    color: '#ff4a00',
    stat: '-35%',
    desc: 'Automated multi-channel appointment reminders that slash no-shows and fill cancellations.',
    problem: 'Healthcare providers and clinics had 25–40% no-show rates because reminder calls were manual and inconsistent. Cancelled slots went unfilled for hours, losing revenue.',
    howItWorks: [
      { step: 'Trigger', desc: 'New appointment booked or reminder window opens (72h, 24h, 2h)' },
      { step: 'Process', desc: 'Patient preferred contact method checked; message personalised with appointment details' },
      { step: 'Output', desc: 'SMS, email, and/or WhatsApp reminder sent; confirmation link included' },
      { step: 'Notify', desc: 'Cancellations trigger waitlist fill automatically; clinic receives daily schedule' },
    ],
    results: [{ big: '-35%', label: 'No-show rate' }, { big: '3 channels', label: 'Multi-touch' }, { big: '+$18K', label: 'Monthly recovery' }],
    techStack: ['Zapier', 'Acuity Scheduling', 'Twilio', 'Mailchimp', 'Google Sheets'],
    related: ['healthcare-patient-intake', 'client-onboarding-pipeline', 'booking-confirmation-flow'],
    flowSteps: [
      { id: 'trigger', label: 'Acuity', sublabel: '72h before appt', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Channel selection', type: 'process' },
      { id: 'output', label: 'SMS + Email', sublabel: 'Reminder sent', type: 'output' },
      { id: 'waitlist', label: 'Waitlist Fill', sublabel: 'Cancel → fill', type: 'output' },
      { id: 'result', label: '-35%', sublabel: 'No-show rate', type: 'result' },
    ],
  },
  {
    slug: 'zapier-ecommerce-inventory-alert',
    title: 'Low Stock Inventory Alert',
    platform: 'Zapier',
    industry: 'E-commerce',
    color: '#ff4a00',
    stat: '0 stockouts',
    desc: 'Real-time low stock alerts with automatic purchase order draft sent to suppliers.',
    problem: 'E-commerce businesses were regularly running out of bestselling SKUs because stock alerts were checked manually and reorder emails to suppliers were written from scratch each time.',
    howItWorks: [
      { step: 'Trigger', desc: 'Shopify inventory drops below reorder threshold for any SKU' },
      { step: 'Process', desc: 'Lead time, sales velocity, and supplier terms checked; reorder quantity calculated' },
      { step: 'Output', desc: 'Draft PO email created and sent to supplier; Slack alert to operations team' },
      { step: 'Notify', desc: 'PO status tracked; expected delivery date added to product page' },
    ],
    results: [{ big: '0', label: 'Stockouts' }, { big: '5min', label: 'PO creation time' }, { big: '+12%', label: 'Inventory efficiency' }],
    techStack: ['Zapier', 'Shopify', 'Gmail', 'Slack', 'Airtable'],
    related: ['marketplace-price-sync', 'supplier-quote-aggregator', 'ecommerce-abandoned-cart'],
    flowSteps: [
      { id: 'trigger', label: 'Shopify', sublabel: 'Stock < threshold', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Calc reorder qty', type: 'process' },
      { id: 'po', label: 'Gmail', sublabel: 'PO draft sent', type: 'output' },
      { id: 'notify', label: 'Slack', sublabel: 'Ops alerted', type: 'output' },
      { id: 'result', label: '0', sublabel: 'Stockouts', type: 'result' },
    ],
  },
  {
    slug: 'zapier-real-estate-valuation',
    title: 'Property Valuation Request Flow',
    platform: 'Zapier',
    industry: 'Real Estate',
    color: '#ff4a00',
    stat: '3h→15min',
    desc: 'Instant valuation request processing: data pull, comparables, and agent briefing in 15 minutes.',
    problem: 'Real estate agents received valuation requests by email and spent 3+ hours pulling comps, researching the market, and preparing a basic report before even speaking to the client.',
    howItWorks: [
      { step: 'Trigger', desc: 'Valuation request received via website form or referral partner' },
      { step: 'Process', desc: 'Property data pulled from portals; comparable sales and rentals identified' },
      { step: 'Output', desc: 'Valuation brief with 5 comparables sent to agent; client receives acknowledgement' },
      { step: 'Notify', desc: 'CRM deal created; follow-up call task booked for agent within 2 hours' },
    ],
    results: [{ big: '15min', label: 'Brief preparation' }, { big: '5 comps', label: 'Auto-sourced' }, { big: '+55%', label: 'Valuations booked' }],
    techStack: ['Zapier', 'HubSpot', 'PropertyFinder API', 'Google Sheets', 'Gmail'],
    related: ['ai-lead-response', 'property-listing-sync', 'real-estate-deal-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Website Form', sublabel: 'Valuation request', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Pull comparables', type: 'process' },
      { id: 'brief', label: 'Gmail', sublabel: 'Agent briefed', type: 'output' },
      { id: 'crm', label: 'HubSpot', sublabel: 'Deal created', type: 'output' },
      { id: 'result', label: '15min', sublabel: 'vs 3h manual', type: 'result' },
    ],
  },
  {
    slug: 'zapier-logistics-pod',
    title: 'Proof of Delivery Automation',
    platform: 'Zapier',
    industry: 'Logistics',
    color: '#ff4a00',
    stat: '100%',
    desc: 'Instant POD collection, PDF generation, and client delivery confirmation — fully paperless.',
    problem: 'Logistics operators were collecting paper PODs from drivers, scanning them, and emailing them manually to clients — a process that took 48+ hours and introduced frequent losses.',
    howItWorks: [
      { step: 'Trigger', desc: 'Driver submits digital POD via mobile app with photo and signature' },
      { step: 'Process', desc: 'POD validated; PDF generated with timestamp, GPS, and signature embedded' },
      { step: 'Output', desc: 'POD PDF emailed to client instantly; invoice triggered in accounting system' },
      { step: 'Notify', desc: 'Delivery confirmed in TMS; client receives WhatsApp notification' },
    ],
    results: [{ big: '100%', label: 'Digital POD rate' }, { big: '<5min', label: 'Client delivery' }, { big: '-100%', label: 'Paper PODs' }],
    techStack: ['Zapier', 'GoFormz', 'Xero', 'WhatsApp API', 'Google Drive'],
    related: ['logistics-shipment-tracking', 'invoice-document-ai', 'supplier-quote-aggregator'],
    flowSteps: [
      { id: 'trigger', label: 'Driver App', sublabel: 'POD submitted', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'PDF generated', type: 'process' },
      { id: 'email', label: 'Gmail', sublabel: 'Client emailed', type: 'output' },
      { id: 'invoice', label: 'Xero', sublabel: 'Invoice triggered', type: 'output' },
      { id: 'result', label: '<5min', sublabel: '100% digital', type: 'result' },
    ],
  },
  {
    slug: 'zapier-agriculture-weather',
    title: 'Weather-Triggered Farm Alerts',
    platform: 'Zapier',
    industry: 'Agriculture',
    color: '#ff4a00',
    stat: '-28%',
    desc: 'Automated weather monitoring with farm-specific alerts for frost, rain, and extreme heat.',
    problem: 'Farmers checked weather forecasts manually and often acted too late to protect crops from frost damage or irrigation waste during rain periods. Alert thresholds were not farm-specific.',
    howItWorks: [
      { step: 'Trigger', desc: 'Weather API polled every 30 minutes for all registered farm locations' },
      { step: 'Process', desc: 'Forecast compared against crop-specific thresholds (frost, heat, wind, rain)' },
      { step: 'Output', desc: 'Farm manager receives WhatsApp alert with specific recommended action' },
      { step: 'Notify', desc: 'Alert log updated; seasonal report generated for planning review' },
    ],
    results: [{ big: '-28%', label: 'Crop losses' }, { big: '30min', label: 'Alert window' }, { big: '100%', label: 'Farm coverage' }],
    techStack: ['Zapier', 'OpenWeather API', 'Twilio', 'WhatsApp API', 'Airtable'],
    related: ['crop-monitoring-alert', 'iot-alert-escalation', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'OpenWeather API', sublabel: 'Every 30min', type: 'trigger' },
      { id: 'process', label: 'Zapier', sublabel: 'Threshold check', type: 'process' },
      { id: 'output', label: 'WhatsApp', sublabel: 'Farm alert', type: 'output' },
      { id: 'log', label: 'Airtable', sublabel: 'Logged', type: 'output' },
      { id: 'result', label: '-28%', sublabel: 'Crop losses', type: 'result' },
    ],
  },

  // ─────────────────────────────────────────────────────────────
  // UiPath AUTOMATIONS (10)
  // ─────────────────────────────────────────────────────────────
  {
    slug: 'uipath-insurance-claims',
    title: 'Insurance Claims Processing',
    platform: 'UiPath',
    industry: 'Finance',
    color: '#f4c400',
    stat: '12d→2d',
    desc: 'RPA bot processes insurance claims end-to-end: validation, data entry, and decision routing.',
    problem: 'Insurance claims processors were manually keying data from claim forms into legacy systems, running eligibility checks across 3 systems, and routing claims based on value thresholds — 12 days average cycle.',
    howItWorks: [
      { step: 'Trigger', desc: 'New claim received via email or portal; bot picks up from queue' },
      { step: 'Process', desc: 'Bot reads form data, validates policy, runs eligibility across all systems' },
      { step: 'Output', desc: 'Auto-approved claims processed immediately; complex claims routed with full context' },
      { step: 'Notify', desc: 'Claimant notified of status; auditor receives daily exception log' },
    ],
    results: [{ big: '2d', label: 'Claims cycle' }, { big: '85%', label: 'Auto-processed' }, { big: '0', label: 'Keying errors' }],
    techStack: ['UiPath', 'SAP', 'Salesforce', 'Python', 'SQL Server'],
    related: ['invoice-document-ai', 'regulatory-compliance-monitor', 'finance-expense-approval'],
    flowSteps: [
      { id: 'trigger', label: 'Claims Queue', sublabel: 'Bot activated', type: 'trigger' },
      { id: 'process', label: 'UiPath RPA', sublabel: 'Multi-system check', type: 'process' },
      { id: 'decision', label: 'Auto-approve', sublabel: '85% resolved', type: 'output' },
      { id: 'route', label: 'Complex Routing', sublabel: 'Adjuster briefed', type: 'output' },
      { id: 'result', label: '2d', sublabel: 'vs 12d cycle', type: 'result' },
    ],
  },
  {
    slug: 'uipath-bank-reconciliation',
    title: 'Bank Reconciliation RPA',
    platform: 'UiPath',
    industry: 'Finance',
    color: '#f4c400',
    stat: '8h→40min',
    desc: 'RPA bot reconciles bank statements against ledger entries across multiple accounts daily.',
    problem: 'Finance teams spent 6–8 hours each month-end reconciling bank statements by hand — matching transactions, investigating discrepancies, and preparing sign-off reports for auditors.',
    howItWorks: [
      { step: 'Trigger', desc: 'Month-end scheduled trigger or on-demand run by finance manager' },
      { step: 'Process', desc: 'Bot downloads statements, maps against ledger, identifies mismatches' },
      { step: 'Output', desc: 'Reconciliation report generated with matched, unmatched, and query items' },
      { step: 'Notify', desc: 'CFO receives sign-off pack; unmatched items assigned to investigator in Jira' },
    ],
    results: [{ big: '40min', label: 'Reconciliation time' }, { big: '99.8%', label: 'Match accuracy' }, { big: '0', label: 'Manual entry' }],
    techStack: ['UiPath', 'SAP FI', 'Excel', 'SQL Server', 'Outlook'],
    related: ['invoice-document-ai', 'revenue-leakage-detector', 'zapier-payment-reminder'],
    flowSteps: [
      { id: 'trigger', label: 'Scheduler', sublabel: 'Month-end run', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Statement pull', type: 'process' },
      { id: 'match', label: 'SAP FI', sublabel: 'Ledger matching', type: 'output' },
      { id: 'report', label: 'Excel Report', sublabel: 'CFO sign-off pack', type: 'output' },
      { id: 'result', label: '40min', sublabel: 'vs 8h manual', type: 'result' },
    ],
  },
  {
    slug: 'uipath-healthcare-records',
    title: 'Patient Records Migration',
    platform: 'UiPath',
    industry: 'Healthcare',
    color: '#f4c400',
    stat: '0 errors',
    desc: 'RPA bot migrates patient records between EMR systems with 100% accuracy and full audit trail.',
    problem: 'Healthcare IT teams spent months on manual data migration projects, copying patient records between EMR systems with high error rates that required expensive remediation.',
    howItWorks: [
      { step: 'Trigger', desc: 'Migration batch scheduled or triggered by IT team for specific patient cohort' },
      { step: 'Process', desc: 'Bot reads source EMR, maps to target schema, validates key fields before write' },
      { step: 'Output', desc: 'Records written to target EMR with checksum validation; audit log generated' },
      { step: 'Notify', desc: 'IT team receives migration report; any validation failures quarantined for review' },
    ],
    results: [{ big: '0', label: 'Migration errors' }, { big: '100%', label: 'Audit coverage' }, { big: '10x', label: 'Speed vs manual' }],
    techStack: ['UiPath', 'Epic EMR', 'Cerner', 'SQL Server', 'Azure'],
    related: ['healthcare-patient-intake', 'zapier-healthcare-appointment', 'regulatory-compliance-monitor'],
    flowSteps: [
      { id: 'trigger', label: 'Migration Job', sublabel: 'Batch scheduled', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Read + map', type: 'process' },
      { id: 'validate', label: 'Checksum', sublabel: 'Field validated', type: 'output' },
      { id: 'write', label: 'Target EMR', sublabel: 'Records written', type: 'output' },
      { id: 'result', label: '0 errors', sublabel: '10x faster', type: 'result' },
    ],
  },
  {
    slug: 'uipath-logistics-customs',
    title: 'Customs Documentation RPA',
    platform: 'UiPath',
    industry: 'Logistics',
    color: '#f4c400',
    stat: '4h→30min',
    desc: 'Automated customs form population, tariff code lookup, and submission across all ports.',
    problem: 'Customs brokers were manually completing HS code lookups, populating customs declarations, and submitting to government portals — 4 hours per shipment during peak season, causing delays.',
    howItWorks: [
      { step: 'Trigger', desc: 'Shipment file created in TMS with goods description and destination' },
      { step: 'Process', desc: 'Bot looks up HS codes, populates declaration form, calculates duties' },
      { step: 'Output', desc: 'Declaration submitted to government portal; reference number logged in TMS' },
      { step: 'Notify', desc: 'Broker receives confirmation; any rejected submissions flagged for manual review' },
    ],
    results: [{ big: '30min', label: 'Per declaration' }, { big: '100%', label: 'Submission rate' }, { big: '-80%', label: 'Broker time' }],
    techStack: ['UiPath', 'CargoWise', 'SAP TM', 'Government Portals', 'Excel'],
    related: ['logistics-shipment-tracking', 'zapier-logistics-pod', 'supplier-quote-aggregator'],
    flowSteps: [
      { id: 'trigger', label: 'TMS', sublabel: 'Shipment created', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'HS code lookup', type: 'process' },
      { id: 'form', label: 'Declaration Form', sublabel: 'Auto-populated', type: 'output' },
      { id: 'submit', label: 'Gov Portal', sublabel: 'Submitted', type: 'output' },
      { id: 'result', label: '30min', sublabel: 'vs 4h manual', type: 'result' },
    ],
  },
  {
    slug: 'uipath-hr-payroll-processing',
    title: 'Payroll Processing RPA',
    platform: 'UiPath',
    industry: 'HR',
    color: '#f4c400',
    stat: '2d→3h',
    desc: 'End-to-end payroll run: data collection, calculations, approval, and bank file — automated.',
    problem: 'Payroll administrators spent 2 days each payroll cycle collecting timesheets, calculating deductions, entering data, and generating bank transfer files — with constant risk of errors.',
    howItWorks: [
      { step: 'Trigger', desc: 'Payroll period closes; bot triggered by finance calendar' },
      { step: 'Process', desc: 'Timesheet data pulled from HRIS; deductions calculated; statutory obligations checked' },
      { step: 'Output', desc: 'Payroll report generated for CFO approval; bank file ready on approval' },
      { step: 'Notify', desc: 'Payslips emailed to employees; GL entries posted to accounting system' },
    ],
    results: [{ big: '3h', label: 'Payroll run time' }, { big: '0', label: 'Calculation errors' }, { big: '100%', label: 'Compliance checks' }],
    techStack: ['UiPath', 'ADP', 'SAP HR', 'Excel', 'Outlook'],
    related: ['hr-onboarding-bot', 'hr-leave-management', 'zapier-job-applicant-screening'],
    flowSteps: [
      { id: 'trigger', label: 'Finance Calendar', sublabel: 'Period closes', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Calculate payroll', type: 'process' },
      { id: 'approve', label: 'CFO Review', sublabel: 'Report approved', type: 'output' },
      { id: 'bank', label: 'Bank File', sublabel: 'Transfer initiated', type: 'output' },
      { id: 'result', label: '3h', sublabel: 'vs 2 days', type: 'result' },
    ],
  },
  {
    slug: 'uipath-real-estate-due-diligence',
    title: 'Property Due Diligence Bot',
    platform: 'UiPath',
    industry: 'Real Estate',
    color: '#f4c400',
    stat: '5d→1d',
    desc: 'RPA bot aggregates title, valuation, planning, and mortgage data into a single due diligence pack.',
    problem: 'Property lawyers and mortgage advisors spent 4–5 days manually pulling information from land registries, planning portals, and valuation systems to build due diligence packs.',
    howItWorks: [
      { step: 'Trigger', desc: 'Property transaction opened in case management system' },
      { step: 'Process', desc: 'Bot queries land registry, planning portal, flood risk, and valuation databases' },
      { step: 'Output', desc: 'Consolidated due diligence pack generated as PDF with all certificates attached' },
      { step: 'Notify', desc: 'Lawyer receives pack with summary; any issues flagged with severity rating' },
    ],
    results: [{ big: '1d', label: 'Due diligence cycle' }, { big: '8 sources', label: 'Auto-queried' }, { big: '-80%', label: 'Legal fees' }],
    techStack: ['UiPath', 'HM Land Registry API', 'Planning Portal', 'Salesforce', 'PDF Tools'],
    related: ['legal-document-automation', 'contract-renewal-alerts', 'property-listing-sync'],
    flowSteps: [
      { id: 'trigger', label: 'Case System', sublabel: 'Transaction opened', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: '8 sources queried', type: 'process' },
      { id: 'pack', label: 'PDF Generator', sublabel: 'Pack assembled', type: 'output' },
      { id: 'notify', label: 'Lawyer Briefed', sublabel: 'Issues flagged', type: 'output' },
      { id: 'result', label: '1d', sublabel: 'vs 5 days', type: 'result' },
    ],
  },
  {
    slug: 'uipath-manufacturing-erp',
    title: 'ERP Data Entry Automation',
    platform: 'UiPath',
    industry: 'Manufacturing',
    color: '#f4c400',
    stat: '6h→0',
    desc: 'RPA bot moves production orders, BOM changes, and inventory updates into ERP automatically.',
    problem: 'Manufacturing teams were manually keying production orders from floor sheets into the ERP, updating bill of materials, and adjusting inventory — 6 hours of data entry per shift.',
    howItWorks: [
      { step: 'Trigger', desc: 'Production data sheet completed on floor or uploaded to shared drive' },
      { step: 'Process', desc: 'Bot reads structured data, validates against master data, and queues entries' },
      { step: 'Output', desc: 'Production orders, BOM updates, and inventory adjustments posted to ERP' },
      { step: 'Notify', desc: 'Production manager receives shift summary; anomalies flagged for QC review' },
    ],
    results: [{ big: '0h', label: 'Manual ERP entry' }, { big: '99.9%', label: 'Data accuracy' }, { big: '+1 shift', label: 'Capacity regained' }],
    techStack: ['UiPath', 'SAP PP', 'Microsoft Dynamics', 'Excel', 'SharePoint'],
    related: ['supplier-quote-aggregator', 'manufacturing-quality-alert', 'kpi-dashboard-report'],
    flowSteps: [
      { id: 'trigger', label: 'SharePoint', sublabel: 'Sheet uploaded', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Validate + queue', type: 'process' },
      { id: 'erp', label: 'SAP PP', sublabel: 'Orders posted', type: 'output' },
      { id: 'report', label: 'Manager Summary', sublabel: 'Anomalies flagged', type: 'output' },
      { id: 'result', label: '0h', sublabel: 'Manual ERP entry', type: 'result' },
    ],
  },
  {
    slug: 'uipath-ecommerce-catalogue',
    title: 'Product Catalogue Update Bot',
    platform: 'UiPath',
    industry: 'E-commerce',
    color: '#f4c400',
    stat: '3h→15min',
    desc: 'RPA bot processes supplier product feeds and updates your catalogue across all systems.',
    problem: 'E-commerce operations teams processed weekly supplier product feeds manually — downloading Excel files, reformatting, updating prices and descriptions, and uploading to multiple platforms.',
    howItWorks: [
      { step: 'Trigger', desc: 'Supplier product feed received via email or FTP' },
      { step: 'Process', desc: 'Bot parses feed, maps to internal schema, identifies new, changed, and discontinued SKUs' },
      { step: 'Output', desc: 'Catalogue updated in PIM, Shopify, and marketplace platforms simultaneously' },
      { step: 'Notify', desc: 'Operations team receives update summary with new SKU count and change log' },
    ],
    results: [{ big: '15min', label: 'Feed processing' }, { big: '100%', label: 'SKU coverage' }, { big: '0', label: 'Manual edits' }],
    techStack: ['UiPath', 'Akeneo PIM', 'Shopify', 'Amazon SP-API', 'Excel'],
    related: ['marketplace-price-sync', 'ecommerce-abandoned-cart', 'supplier-quote-aggregator'],
    flowSteps: [
      { id: 'trigger', label: 'Email / FTP', sublabel: 'Supplier feed in', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Parse + map', type: 'process' },
      { id: 'pim', label: 'Akeneo PIM', sublabel: 'Master updated', type: 'output' },
      { id: 'channels', label: 'Shopify + Amazon', sublabel: 'Synced', type: 'output' },
      { id: 'result', label: '15min', sublabel: 'vs 3h manual', type: 'result' },
    ],
  },
  {
    slug: 'uipath-travel-visa-processing',
    title: 'Visa Application Processing',
    platform: 'UiPath',
    industry: 'Travel',
    color: '#f4c400',
    stat: '2h→20min',
    desc: 'RPA bot completes visa applications across government portals — accurate, fast, audit-ready.',
    problem: 'Travel management companies spent 2+ hours per visa application navigating government portals, copying data from client passports and forms, and uploading documents one by one.',
    howItWorks: [
      { step: 'Trigger', desc: 'Visa request received with client documents and travel details' },
      { step: 'Process', desc: 'Bot navigates government portal, populates all form fields, uploads required documents' },
      { step: 'Output', desc: 'Application submitted; reference number logged; payment processed if required' },
      { step: 'Notify', desc: 'Client receives confirmation; travel consultant alerted with status and timeline' },
    ],
    results: [{ big: '20min', label: 'Per application' }, { big: '0', label: 'Data entry errors' }, { big: '+5x', label: 'Applications/day' }],
    techStack: ['UiPath', 'Government Portals', 'Salesforce', 'Stripe', 'SharePoint'],
    related: ['booking-confirmation-flow', 'travel-itinerary-builder', 'client-onboarding-pipeline'],
    flowSteps: [
      { id: 'trigger', label: 'Visa Request', sublabel: 'Documents received', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Portal navigation', type: 'process' },
      { id: 'form', label: 'Gov Portal', sublabel: 'Form submitted', type: 'output' },
      { id: 'notify', label: 'Salesforce', sublabel: 'Client confirmed', type: 'output' },
      { id: 'result', label: '20min', sublabel: 'vs 2h manual', type: 'result' },
    ],
  },
  {
    slug: 'uipath-agriculture-subsidy',
    title: 'Agricultural Subsidy Claims',
    platform: 'UiPath',
    industry: 'Agriculture',
    color: '#f4c400',
    stat: '3d→4h',
    desc: 'RPA bot completes government subsidy claim forms from farm data — maximise entitlement automatically.',
    problem: 'Farming businesses and agricultural consultants spent 2–3 days per claim manually pulling acreage data, crop records, and livestock counts from multiple sources to populate government subsidy forms.',
    howItWorks: [
      { step: 'Trigger', desc: 'Claim window opens; bot triggered with farm reference numbers' },
      { step: 'Process', desc: 'Bot pulls farm data from land records, crop diaries, and livestock registers' },
      { step: 'Output', desc: 'Government claim forms pre-populated; supporting documents attached and submitted' },
      { step: 'Notify', desc: 'Farmer receives claim summary; consultant receives sign-off request with entitlement value' },
    ],
    results: [{ big: '4h', label: 'Claim preparation' }, { big: '100%', label: 'Entitlement captured' }, { big: '0', label: 'Missed deadlines' }],
    techStack: ['UiPath', 'Government Rural Portal', 'Excel', 'SharePoint', 'Outlook'],
    related: ['crop-monitoring-alert', 'iot-alert-escalation', 'zapier-agriculture-weather'],
    flowSteps: [
      { id: 'trigger', label: 'Claim Window', sublabel: 'Season opens', type: 'trigger' },
      { id: 'process', label: 'UiPath Bot', sublabel: 'Farm data pull', type: 'process' },
      { id: 'form', label: 'Rural Portal', sublabel: 'Form submitted', type: 'output' },
      { id: 'notify', label: 'Consultant', sublabel: 'Sign-off request', type: 'output' },
      { id: 'result', label: '4h', sublabel: 'vs 3 days', type: 'result' },
    ],
  },
];
