/* eslint-disable */
export interface Project {
  slug: string;
  tags: string[];
  title: string;
  client: string;
  desc: string;
  stat: string;
  challenge: string;
  solution: string;
  techStack: string[];
  results: { b: string; s: string }[];
}

export const PROJECTS: Project[] = [
  {
    slug: 'bayut-premium-ai',
    tags: ['Real Estate', 'AI'],
    title: 'Bayut Premium AI',
    client: 'Real estate portal, Dubai',
    desc: 'AI lead qualification and WhatsApp automation for a premium Dubai property portal. Every enquiry scored and responded to in 90 seconds.',
    stat: '4h → 90s response',
    challenge: 'A high-volume Dubai property portal was receiving 800+ enquiries per day across WhatsApp, email, and web forms. Agents were spending 3–4 hours daily triaging messages, and serious buyers were waiting hours for a response — by which time many had moved to a competitor. The manual process created inconsistent tone, missed follow-ups, and no visibility into lead quality.',
    solution: 'We built an AI lead qualification pipeline that intercepts every inbound enquiry in real time. A GPT-4o model reads the message, scores intent (hot/warm/cold), extracts buyer requirements, and generates a personalised WhatsApp response within 90 seconds — 24 hours a day, 7 days a week. Hot leads are escalated to an agent with a full context brief. The entire flow runs on n8n with a HubSpot CRM integration, and a real-time dashboard gives the sales manager full visibility into volume, quality, and agent response times.',
    techStack: ['GPT-4o', 'WhatsApp Business API', 'n8n', 'HubSpot CRM', 'Node.js', 'PostgreSQL'],
    results: [
      { b: '90s', s: 'Avg. response time' },
      { b: '94%', s: 'Enquiries handled automatically' },
      { b: '+38%', s: 'Qualified leads per month' },
    ],
  },
  {
    slug: 'agri-novatex-iot',
    tags: ['Agriculture', 'IoT'],
    title: 'Agri Novatex IoT',
    client: 'Precision farming, Romania',
    desc: 'Greenhouse sensor platform monitoring 400 hectares. Real-time soil, moisture, and temperature alerts with automated escalation.',
    stat: 'Zero missed events',
    challenge: 'An industrial farming operation in Romania was managing 400 hectares of greenhouses with a patchwork of manual sensor readings taken twice daily by field staff. Critical threshold breaches — temperature spikes, irrigation failures, soil nutrient drops — were often discovered hours after the damage had begun. A single missed alert during a heatwave had already cost the business a significant crop loss.',
    solution: 'We designed and deployed a full IoT telemetry platform integrating MQTT-connected sensors across the site into a centralised Node.js processing engine. Sensor readings stream every 60 seconds into a time-series database. A rules engine evaluates each reading against configurable thresholds, classifies severity, and fires automated alerts via SMS, email, and Slack to the correct responder based on location and shift schedule. All alert history is logged for compliance and used to train threshold calibration over time.',
    techStack: ['MQTT', 'Node.js', 'InfluxDB', 'Twilio SMS', 'Slack API', 'Grafana'],
    results: [
      { b: '400ha', s: 'Monitored continuously' },
      { b: '<3min', s: 'Alert-to-notification time' },
      { b: '0', s: 'Critical events missed' },
    ],
  },
  {
    slug: 'ranjet-aviation',
    tags: ['Travel', 'Custom Dev'],
    title: 'Ranjet Aviation',
    client: 'Private jet charter, Dubai',
    desc: 'Custom booking and fleet management system with real-time availability, multi-currency pricing, and automated crew scheduling.',
    stat: '100% manual work cut',
    challenge: 'A Dubai-based private jet charter operator was managing fleet availability, crew scheduling, and client bookings entirely through spreadsheets and WhatsApp group chats. Double-bookings were a recurring problem, pricing was inconsistently applied across currencies, and the operations director spent 6+ hours a day coordinating manually. The business was turning down charter requests simply because they could not track capacity reliably.',
    solution: 'We built a bespoke operations platform covering the full booking lifecycle: real-time fleet availability calendar, multi-currency pricing engine, automated crew assignment based on qualifications and shift rules, and a client-facing quote portal. The system integrates with the company\'s maintenance schedule to block unavailable aircraft automatically. Automated confirmation emails, crew briefings, and client itineraries are generated and sent at each stage without manual intervention.',
    techStack: ['Next.js', 'PostgreSQL', 'Stripe', 'Resend', 'Node.js', 'Tailwind CSS'],
    results: [
      { b: '0', s: 'Double-bookings since launch' },
      { b: '6h', s: 'Daily admin time eliminated' },
      { b: '4.9★', s: 'Client satisfaction rating' },
    ],
  },
  {
    slug: 'hayguard-crm',
    tags: ['Automation', 'CRM'],
    title: 'HayGuard CRM',
    client: 'Professional services, Milan',
    desc: 'End-to-end client onboarding automation integrated with HubSpot. When a deal closes, full onboarding fires in 2 minutes.',
    stat: 'Onboarding time cut 70%',
    challenge: 'A Milan-based professional services firm was losing an average of two full working days per new client onboarding. Once a deal was marked Won in HubSpot, an ops team member manually triggered welcome emails, created Notion workspaces, sent document request forms, and scheduled kick-off calls. With 15–20 new clients per month, the process was consuming a full-time equivalent of ops capacity — and client experience varied depending on who was handling the task.',
    solution: 'We built a trigger-based automation that fires the moment a deal is marked Won in HubSpot. Within 2 minutes: a branded welcome email is sent to the client, a pre-populated Notion workspace is created from template, a DocuSign contract envelope is dispatched, and a Google Calendar kick-off invite is created and shared. A Slack notification with the full client brief is posted to the account manager\'s channel. The entire sequence requires zero manual input.',
    techStack: ['HubSpot', 'n8n', 'Notion API', 'DocuSign', 'Google Calendar API', 'Slack API'],
    results: [
      { b: '2min', s: 'Full onboarding start time' },
      { b: '70%', s: 'Ops time saved per client' },
      { b: '0', s: 'Manual steps required' },
    ],
  },
  {
    slug: 'remax-gulf',
    tags: ['Digital Transformation'],
    title: 'RE/MAX Gulf',
    client: 'Real estate brokerage, Dubai',
    desc: 'Full digital transformation for a 50-agent brokerage. CRM rollout, lead automation, agent training programme, KPI reporting.',
    stat: '$2.1M pipeline added',
    challenge: 'A 50-agent RE/MAX franchise in Dubai was operating without a CRM, using a mix of personal WhatsApp groups, Excel trackers, and paper files to manage the sales pipeline. Leads from Bayut, PropertyFinder, and direct referrals were landing in five different inboxes with no central routing. Management had no real-time visibility into agent performance, and high-value leads were routinely falling through the gaps.',
    solution: 'We led a 12-week digital transformation programme: full HubSpot CRM rollout with custom property pipelines, automated lead routing from all portals and ad channels, a 3-day agent training programme with recorded modules, a weekly KPI report auto-generated from CRM data and delivered to management every Monday, and a performance dashboard on the office screen updated in real time. We also implemented a WhatsApp AI layer for initial lead response during out-of-office hours.',
    techStack: ['HubSpot', 'n8n', 'Google Data Studio', 'WhatsApp Business API', 'Zapier', 'Google Sheets'],
    results: [
      { b: '50', s: 'Agents onboarded to CRM' },
      { b: '$2.1M', s: 'New pipeline in 90 days' },
      { b: '3×', s: 'Lead visibility increase' },
    ],
  },
  {
    slug: 'tergo-ai-suite',
    tags: ['AI', 'Custom Dev'],
    title: 'Tergo AI Suite',
    client: 'Multi-market hospitality',
    desc: 'Proprietary AI toolsuite for hospitality clients — guest communication AI, automated review responses, booking channel sync.',
    stat: '12k+ tasks/month',
    challenge: 'Multiple hospitality clients across Dubai and Romania were each independently managing guest communications, online review responses, and multi-channel booking availability — all manually. The repetitive nature of the work (responding to similar guest queries, templated review replies, manual OTA calendar updates) was consuming 30+ staff hours per property per week, and the inconsistency in tone and speed was impacting review scores.',
    solution: 'We built and now maintain a proprietary multi-tenant AI toolsuite deployed across 8 hospitality clients. The suite includes: a guest communication AI trained on each property\'s tone and policies, an automated review response engine for TripAdvisor, Google, and Booking.com, and a real-time booking channel sync that keeps availability consistent across all OTAs. Each client gets a custom-branded dashboard with usage metrics. The platform is hosted on our infrastructure and updated centrally.',
    techStack: ['GPT-4o', 'Next.js', 'PostgreSQL', 'Booking.com API', 'Airbnb API', 'Vercel'],
    results: [
      { b: '12k+', s: 'Tasks automated per month' },
      { b: '99.9%', s: 'Platform uptime' },
      { b: '8', s: 'Active clients on platform' },
    ],
  },
  {
    slug: 'luxstay-dubai',
    tags: ['Travel', 'Automation'],
    title: 'LuxStay Dubai',
    client: 'Short-term rentals, Dubai',
    desc: 'Airbnb and Booking.com channel manager automation with real-time availability sync and automated guest communications.',
    stat: 'Sync errors → zero',
    challenge: 'A short-term rental operator managing 24 luxury units in Dubai was experiencing frequent double-bookings due to calendar sync failures between Airbnb, Booking.com, and their direct booking website. Guest communication was inconsistent — late check-in instructions, missed cleaning team notifications, and delayed review requests were costing them in ratings and repeat bookings. Each calendar update required a manual refresh across three platforms.',
    solution: 'We built a centralised availability hub that maintains a single source of truth for all 24 units. Any booking or block from any channel triggers an instant sync across all other channels via their respective APIs. An automated guest communication sequence fires at booking confirmation, 48 hours before check-in, day-of arrival, and post-checkout — personalised per unit. Cleaning team notifications and review request emails are also automated on checkout trigger.',
    techStack: ['Airbnb API', 'Booking.com API', 'n8n', 'PostgreSQL', 'Resend', 'Twilio'],
    results: [
      { b: '0', s: 'Double-bookings since launch' },
      { b: '4.92★', s: 'Average review rating' },
      { b: '24', s: 'Units fully automated' },
    ],
  },
  {
    slug: 'greenfield-farms',
    tags: ['Agriculture', 'IoT'],
    title: 'GreenField Farms',
    client: 'Crop monitoring, Romania',
    desc: 'Crop monitoring and automated irrigation alert system. Sensor data triggers precise irrigation schedules and escalation alerts.',
    stat: '3 critical failures prevented',
    challenge: 'A Romanian crop farm spanning mixed arable and polytunnel growing areas had invested in soil moisture sensors but was reading the data manually from a web dashboard twice per day. During an unusually dry summer, slow response to soil moisture dips led to a significant crop loss in one field. The farm manager recognised that reactive manual monitoring was insufficient and that the sensor investment needed to be backed by intelligent automation.',
    solution: 'We integrated the existing sensor network with a custom alert engine. Soil moisture, temperature, and rainfall readings are evaluated in real time against crop-specific threshold profiles. When readings breach thresholds, the system determines irrigation priority, schedules pump activation via the existing irrigation controller API, and notifies the field manager with a concise context brief. A weekly summary report is emailed to the farm owner every Sunday with trend analysis and upcoming weather-adjusted recommendations.',
    techStack: ['MQTT', 'Python', 'InfluxDB', 'Twilio SMS', 'OpenWeather API', 'Resend'],
    results: [
      { b: '3', s: 'Critical failures prevented in Y1' },
      { b: '22%', s: 'Water usage reduction' },
      { b: '100%', s: 'Sensor uptime' },
    ],
  },
  {
    slug: 'claimsfast',
    tags: ['Finance', 'AI'],
    title: 'ClaimsFast',
    client: 'Insurance, UAE',
    desc: 'Insurance document AI processing pipeline. Claims documents are read, extracted, validated and routed automatically.',
    stat: 'Manual entry eliminated',
    challenge: 'A UAE insurance intermediary was processing 200–300 claims documents per week, with staff manually extracting policy numbers, claim types, damage descriptions, and supporting evidence from PDFs, scanned forms, and photos. A single claims processor was handling 40+ documents per day, with extraction errors creating downstream delays, compliance flags, and customer complaints about slow resolution times.',
    solution: 'We built an AI document processing pipeline that ingests claims submissions from email, portal uploads, and WhatsApp. A vision-capable AI model reads each document — regardless of format — extracts the structured data fields, validates them against the policy database, flags incomplete or conflicting submissions, and routes clean claims to the correct team queue with a full data brief. Human review is only required for flagged exceptions, reducing total staff time per claim from 12 minutes to under 2 minutes.',
    techStack: ['GPT-4o Vision', 'Python', 'AWS S3', 'PostgreSQL', 'n8n', 'Resend'],
    results: [
      { b: '83%', s: 'Reduction in processing time' },
      { b: '0', s: 'Manual data entry required' },
      { b: '99.1%', s: 'Extraction accuracy' },
    ],
  },
  {
    slug: 'nexus-law',
    tags: ['Legal', 'Automation'],
    title: 'Nexus Law',
    client: 'Law firm, Milan',
    desc: 'Contract review and renewal automation. AI monitors contract expiry dates and triggers review workflows automatically.',
    stat: 'Zero missed renewals',
    challenge: 'A Milan-based law firm was managing 400+ active client contracts stored across a shared drive with no centralised expiry tracking. Renewal reminders were maintained in an Excel spreadsheet updated manually by a paralegal. The firm had already experienced two instances where client contracts lapsed without renewal — one resulting in a dispute. The managing partner identified contract lifecycle management as a critical operational risk.',
    solution: 'We built a contract intelligence system that ingests PDFs from the firm\'s shared drive, extracts key dates, parties, and renewal terms using an AI document reader, and maintains a live contract register in a structured database. 90, 30, and 7 days before each contract\'s expiry or renewal window, automated notifications are sent to the responsible partner with a context brief and one-click actions to extend, flag for review, or archive. The system also generates a monthly contract status report for the partners\' meeting.',
    techStack: ['Claude API', 'Python', 'PostgreSQL', 'n8n', 'Resend', 'Google Drive API'],
    results: [
      { b: '0', s: 'Missed renewals since launch' },
      { b: '400+', s: 'Contracts under management' },
      { b: '3', s: 'Alert tiers per contract' },
    ],
  },
  {
    slug: 'proptrack-uae',
    tags: ['Real Estate', 'Automation'],
    title: 'PropTrack UAE',
    client: 'Property tech, Dubai',
    desc: 'Real-time property listing sync across 6 portals including Bayut, PropertyFinder, and Dubizzle. Zero manual updates.',
    stat: 'Listing errors → zero',
    challenge: 'A Dubai property management company was maintaining listings across Bayut, PropertyFinder, Dubizzle, Houza, JustProperty, and their own website — six separate platforms each requiring manual updates whenever a price, availability status, or description changed. An average of 15 updates per day was taking a full-time staff member 3+ hours to execute, and despite the effort, listing inconsistencies were constant — confusing buyers and generating complaints.',
    solution: 'We built a listing syndication layer on top of the company\'s property management database. Any change in the master record — price update, status change, new photo, description edit — triggers an automated push to all six portals via their respective APIs. Failed syncs are retried with exponential backoff and flagged in a Slack alert if unresolved after 3 attempts. The team now maintains one record; all portals update in under 60 seconds.',
    techStack: ['Node.js', 'PostgreSQL', 'Bayut API', 'PropertyFinder API', 'n8n', 'Slack API'],
    results: [
      { b: '0', s: 'Listing inconsistencies' },
      { b: '<60s', s: 'Portal sync time' },
      { b: '6', s: 'Portals synced from one source' },
    ],
  },
  {
    slug: 'aquapure-industries',
    tags: ['Industrial', 'IoT'],
    title: 'AquaPure Industries',
    client: 'Water treatment, Romania',
    desc: 'Water quality IoT monitoring and escalation alert system. pH, turbidity, and chemical levels monitored 24/7.',
    stat: '3-minute alert response',
    challenge: 'A Romanian water treatment facility was operating with hourly manual sampling for pH, turbidity, chlorine, and dissolved oxygen levels. The 60-minute gap between readings created a significant window in which water quality could deteriorate beyond acceptable limits before being detected. A regulatory audit had highlighted this gap as a compliance risk, and the facility faced potential fines if a quality breach went undetected and unreported.',
    solution: 'We deployed a continuous IoT monitoring system integrating probe-based sensors with a real-time processing engine. Readings are taken every 30 seconds and evaluated against regulatory compliance thresholds as well as tighter internal control limits. Breaches trigger a multi-tier escalation: Level 1 alerts go to the shift supervisor via SMS, Level 2 (sustained breach) escalates to the plant manager, and Level 3 (critical) activates the emergency protocol and logs a compliance incident report automatically. All data is retained for regulatory reporting.',
    techStack: ['MQTT', 'Node.js', 'InfluxDB', 'Twilio SMS', 'PagerDuty', 'Grafana'],
    results: [
      { b: '<3min', s: 'Alert response time' },
      { b: '100%', s: 'Regulatory compliance maintained' },
      { b: '48×', s: 'More frequent than manual sampling' },
    ],
  },
  {
    slug: 'medrecord-ai',
    tags: ['Healthcare', 'AI'],
    title: 'MedRecord AI',
    client: 'Healthcare provider, UAE',
    desc: 'Patient document extraction and routing pipeline. Medical records processed by AI, routed to the correct department automatically.',
    stat: 'Processing time cut 80%',
    challenge: 'A UAE private healthcare provider was receiving 150+ patient documents per day — referral letters, lab results, imaging reports, discharge summaries — all arriving via email, fax-to-PDF, and patient portal upload. Admin staff were manually reading each document, identifying its type, extracting patient identifiers, and forwarding to the relevant clinical department. The process consumed 4 full-time admin staff and created an average 2-hour delay from receipt to clinical team visibility.',
    solution: 'We built a document intelligence pipeline that intercepts every incoming document regardless of source. A vision-capable AI classifies the document type, extracts patient name, ID number, referring clinician, and clinical priority indicators. A routing rules engine maps the document type and department flag to the correct clinical inbox and sends a structured notification to the team. Documents requiring urgent attention are flagged with a priority indicator. Full audit trail maintained for compliance.',
    techStack: ['GPT-4o Vision', 'Python', 'AWS S3', 'PostgreSQL', 'n8n', 'Resend'],
    results: [
      { b: '80%', s: 'Processing time reduction' },
      { b: '<15min', s: 'Document-to-clinician time' },
      { b: '0', s: 'Mis-routed documents in 6 months' },
    ],
  },
  {
    slug: 'supplylink',
    tags: ['Logistics', 'Custom Dev'],
    title: 'SupplyLink',
    client: 'Manufacturing, Romania',
    desc: 'Supplier quote aggregation and comparison tool. RFQs sent automatically, responses aggregated, best quotes surfaced.',
    stat: 'Quote turnaround: 5d → 6h',
    challenge: 'A Romanian manufacturing company was issuing 80–120 Requests for Quotation (RFQs) per month across a 35-supplier network. Each RFQ was manually drafted in Excel, emailed individually, and responses were collected in a shared inbox where a procurement officer spent hours compiling and comparing quotes. The manual cycle averaged 5 business days from RFQ issue to award decision — a bottleneck that was delaying production schedules.',
    solution: 'We built SupplyLink, a custom procurement platform that manages the full RFQ lifecycle. Procurement staff configure the item, quantity, and deadline in a simple form; the system generates individual branded RFQ emails and sends them to the relevant supplier subset automatically. Supplier responses — whether via email reply, portal login, or CSV upload — are parsed, normalised, and loaded into a side-by-side comparison view. A recommendation engine highlights the optimal quote based on price, lead time, and supplier performance history.',
    techStack: ['Next.js', 'PostgreSQL', 'Resend', 'n8n', 'Python', 'Tailwind CSS'],
    results: [
      { b: '6h', s: 'Average quote turnaround (was 5 days)' },
      { b: '35', s: 'Suppliers on platform' },
      { b: '11%', s: 'Average cost reduction through competition' },
    ],
  },
  {
    slug: 'talentflow',
    tags: ['HR', 'Automation'],
    title: 'TalentFlow',
    client: 'HR platform, multi-market',
    desc: 'HR onboarding automation platform. New hire setup across Slack, Notion, BambooHR, and calendar — automated end to end.',
    stat: 'New hire setup: 2d → 45min',
    challenge: 'A fast-growing tech company operating across Dubai, Bucharest, and Milan was taking an average of 2 full working days to fully onboard a new hire — setting up accounts, sending welcome documentation, creating Notion workspaces, assigning Slack channels, and scheduling first-week meetings. With 8–12 new hires per month, HR was spending over 25% of their time on administrative onboarding tasks, and new joiners were frequently reporting a poor first-day experience due to missing access or documentation.',
    solution: 'We built TalentFlow, a trigger-based onboarding automation that fires when a new hire is added to BambooHR. The system automatically creates the Slack account with correct channel assignments, generates a Notion workspace from the role-specific template, sends a personalised welcome email with a first-week guide, creates Google Calendar events for all orientation sessions, and posts an introduction message to the team channel on day one. Market-specific variations (Dubai/Romania/Milan) are handled via conditional logic.',
    techStack: ['BambooHR API', 'Slack API', 'Notion API', 'Google Calendar API', 'n8n', 'Resend'],
    results: [
      { b: '45min', s: 'Full new hire setup (was 2 days)' },
      { b: '96%', s: 'New hire satisfaction score' },
      { b: '0', s: 'Missing accounts on day one' },
    ],
  },
  {
    slug: 'skyroute',
    tags: ['Travel', 'Custom Dev'],
    title: 'SkyRoute',
    client: 'Flight operations, Dubai',
    desc: 'Flight operations management system with crew scheduling, maintenance tracking, compliance monitoring, and client communications.',
    stat: '100% manual scheduling cut',
    challenge: 'A Dubai flight operations company managing a mixed charter and cargo fleet had no integrated operations system. Crew scheduling was managed in a shared spreadsheet, maintenance records lived in a separate system with no link to scheduling, compliance certificate expiry was tracked in a third Excel file, and client trip confirmations were sent manually by the ops team. The lack of integration meant crew were occasionally assigned to aircraft they were not qualified to operate, and one near-miss on a compliance certificate had triggered an internal review.',
    solution: 'We built SkyRoute, a bespoke flight operations platform. The system maintains crew profiles with qualification matrices and automatically validates crew-aircraft assignment. Maintenance schedules are linked to aircraft availability, blocking scheduling when an aircraft is due for service. A compliance calendar tracks all certificate and licence expiry dates with automated renewal reminders. Client itineraries, crew briefings, and ground handler notifications are generated and sent automatically at each workflow stage.',
    techStack: ['Next.js', 'PostgreSQL', 'Node.js', 'Resend', 'Tailwind CSS', 'Vercel'],
    results: [
      { b: '0', s: 'Scheduling conflicts since launch' },
      { b: '100%', s: 'Compliance certificate coverage' },
      { b: '4h', s: 'Daily ops admin eliminated' },
    ],
  },
  {
    slug: 'coastal-villas',
    tags: ['Real Estate', 'AI'],
    title: 'Coastal Villas',
    client: 'Luxury villa rentals, UAE',
    desc: 'WhatsApp AI system for luxury villa rentals. Enquiries handled, qualified, and responded to in multiple languages 24/7.',
    stat: 'Response time: 4h → 2min',
    challenge: 'A luxury villa rental portfolio in the UAE was receiving high-value enquiries via WhatsApp at all hours — particularly from international guests in different time zones — and responding only during business hours. A typical enquiry-to-response delay of 3–4 hours was causing them to lose bookings to competitors who responded faster. The business also needed responses in Arabic, Russian, and Chinese, which required a translator and added further delays.',
    solution: 'We deployed a WhatsApp AI agent trained on the villa portfolio — pricing, availability, amenities, booking terms, and property details for each villa. The agent detects the guest\'s language, responds in kind, qualifies the enquiry (dates, group size, budget), and checks availability in real time. High-intent enquiries are automatically escalated to a human agent with a full conversation summary. The AI handles everything else: FAQs, photo requests, area recommendations.',
    techStack: ['GPT-4o', 'WhatsApp Business API', 'n8n', 'PostgreSQL', 'Resend', 'Node.js'],
    results: [
      { b: '2min', s: 'Avg. response time (was 4h)' },
      { b: '4', s: 'Languages handled (EN/AR/RU/ZH)' },
      { b: '+29%', s: 'Booking conversion rate' },
    ],
  },
  {
    slug: 'pharmatrack',
    tags: ['Healthcare', 'Automation'],
    title: 'PharmaTrack',
    client: 'Pharma distributor, UAE',
    desc: 'Regulatory compliance monitor for pharmaceutical distribution. Changes to regulations flagged and routed to compliance team.',
    stat: '100% compliance coverage',
    challenge: 'A pharmaceutical distribution company operating in the UAE was relying on a compliance officer to manually monitor updates from the Ministry of Health, MOHAP circulars, and international regulatory bodies. The volume of regulatory publications — often in both Arabic and English — made comprehensive monitoring practically impossible for a single person. Two instances of delayed compliance response in 18 months had resulted in costly product holds.',
    solution: 'We built an automated regulatory intelligence monitor that scrapes and indexes publications from MOHAP, WHO, EMA, and three other regulatory sources on a 4-hourly cycle. AI extracts the key change, affected product categories, effective date, and required action. Relevant changes are automatically classified by impact level and routed to the appropriate compliance team member with a plain-English summary and original source link. A compliance log is maintained for audit purposes.',
    techStack: ['Python', 'Claude API', 'PostgreSQL', 'n8n', 'Resend', 'Playwright'],
    results: [
      { b: '100%', s: 'Regulatory sources monitored' },
      { b: '<4h', s: 'Detection-to-notification time' },
      { b: '0', s: 'Compliance misses since deployment' },
    ],
  },
  {
    slug: 'finvault',
    tags: ['Finance', 'AI'],
    title: 'FinVault',
    client: 'Finance company, Dubai',
    desc: 'Revenue leakage detection system. AI analyses transactions and flags anomalies, discrepancies, and missed billing events.',
    stat: 'AED 180K recovered in Q1',
    challenge: 'A Dubai financial services company suspected it was losing revenue to billing gaps — services delivered but not invoiced, discounts applied incorrectly, and duplicate charges going unchallenged. With 2,000+ monthly transactions across multiple service lines, manual reconciliation was performed quarterly and was catching only the most obvious issues. The CFO estimated leakage was likely in the hundreds of thousands of AED annually but lacked a systematic way to detect it.',
    solution: 'We built a revenue integrity engine that connects to the company\'s accounting system, CRM, and service delivery records. An AI model analyses every transaction against the expected billing event, flags mismatches, unusually large discounts, un-billed service completions, and duplicate entries. Each anomaly is scored by potential revenue impact and routed to the finance team as a daily digest with one-click resolution actions. In Q1, AED 180K in previously undetected leakage was identified and recovered.',
    techStack: ['Python', 'GPT-4o', 'PostgreSQL', 'Xero API', 'HubSpot API', 'n8n'],
    results: [
      { b: 'AED 180K', s: 'Recovered in Q1' },
      { b: '2,000+', s: 'Transactions analysed monthly' },
      { b: '98.4%', s: 'Anomaly detection accuracy' },
    ],
  },
  {
    slug: 'marketpulse',
    tags: ['SaaS', 'Automation'],
    title: 'MarketPulse',
    client: 'SaaS company, Romania',
    desc: 'Automated weekly competitor intelligence report. Web scraping, analysis, and formatted PDF delivered every Monday morning.',
    stat: '20 hrs/wk reclaimed',
    challenge: 'A Romanian SaaS company was paying a junior analyst 20 hours per week to manually track 8 competitors: monitoring pricing pages, feature announcements, job postings, review scores, and social media for signals of strategic change. The report was inconsistent in depth, prone to delays, and the analyst\'s time was increasingly being viewed as an inefficient use of human capital. Leadership wanted competitive intelligence delivered faster and more consistently.',
    solution: 'We built MarketPulse, an automated competitor intelligence pipeline. Every Monday at 5AM, the system scrapes pricing pages, G2 and Capterra review scores, LinkedIn job postings, and blog RSS feeds for each of the 8 tracked competitors. Changes since the previous week are detected and categorised (pricing change, new feature, hiring signal, reputation shift). An AI model writes a concise analysis of the week\'s competitive landscape. A formatted PDF report is generated and emailed to the leadership team before 8AM.',
    techStack: ['Python', 'Playwright', 'Claude API', 'PostgreSQL', 'WeasyPrint', 'n8n'],
    results: [
      { b: '20h', s: 'Analyst time reclaimed per week' },
      { b: '8', s: 'Competitors tracked continuously' },
      { b: '100%', s: 'On-time delivery since launch' },
    ],
  },
  {
    slug: 'dubaidevs',
    tags: ['CTO Advisory'],
    title: 'DubaiDevs',
    client: 'Tech startup, Dubai',
    desc: 'CTO advisory engagement and engineering team build. Architecture design, tech stack selection, and senior developer hiring.',
    stat: 'MVP shipped 6 weeks early',
    challenge: 'A Dubai tech startup had secured seed funding to build a B2B SaaS platform but had no technical co-founder or CTO. The founding team — commercial and domain specialists — were being offered wildly varying technical proposals from development agencies, with costs ranging from AED 150K to AED 800K for what appeared to be similar scope. They needed a trusted technical voice to assess proposals, define the architecture, and build the in-house team before hiring an internal CTO.',
    solution: 'We embedded as fractional CTO for a 6-month engagement. We defined the system architecture, selected the tech stack (Next.js, PostgreSQL, Railway, Vercel), reviewed and reduced the agency proposals to a fair AED 220K scope, hired and onboarded two senior engineers, established the development workflow (GitHub, Linear, weekly demos), and remained available as the technical decision-maker throughout the MVP build. The MVP launched 6 weeks ahead of the original agency timeline.',
    techStack: ['Next.js', 'PostgreSQL', 'Railway', 'Vercel', 'GitHub', 'Linear'],
    results: [
      { b: '6 wks', s: 'Ahead of original timeline' },
      { b: 'AED 580K', s: 'Saved vs. highest agency quote' },
      { b: '2', s: 'Senior engineers hired and onboarded' },
    ],
  },
  {
    slug: 'fleetwise',
    tags: ['Logistics', 'IoT'],
    title: 'FleetWise',
    client: 'Fleet operator, UAE',
    desc: 'Vehicle telematics and maintenance alert automation. Real-time GPS, engine diagnostics, and predictive maintenance alerts.',
    stat: 'Breakdowns reduced 45%',
    challenge: 'A UAE fleet operator managing 60 commercial vehicles was reactive in its maintenance approach — vehicles were serviced on a calendar schedule regardless of actual usage and engine condition, and breakdowns were occurring 3–4 times per month on average. Each roadside breakdown cost an average of AED 4,200 in recovery, repair, and lost delivery revenue. The operations manager had no real-time visibility into vehicle location or engine health.',
    solution: 'We deployed OBD-II telematics units across the fleet and built a monitoring and alerting platform on top. Engine fault codes, mileage, fuel consumption, battery voltage, and GPS location are streamed in real time. A predictive maintenance model analyses engine diagnostic patterns and flags vehicles requiring attention before failure. Maintenance alerts are dispatched to the workshop manager 500km before a service is due, and driver behaviour scores are generated weekly per driver.',
    techStack: ['MQTT', 'Node.js', 'InfluxDB', 'Google Maps API', 'Twilio SMS', 'Grafana'],
    results: [
      { b: '45%', s: 'Reduction in breakdowns' },
      { b: 'AED 88K', s: 'Saved in Year 1 recovery costs' },
      { b: '60', s: 'Vehicles monitored in real time' },
    ],
  },
  {
    slug: 'retailsync',
    tags: ['E-commerce', 'Automation'],
    title: 'RetailSync',
    client: 'E-commerce retailer, Romania',
    desc: 'E-commerce price and inventory sync across WooCommerce, Amazon, and Noon. Real-time updates, zero manual intervention.',
    stat: 'Sync errors → zero',
    challenge: 'A Romanian e-commerce retailer selling across WooCommerce, Amazon.ae, and Noon was managing product data in three separate dashboards. Price and stock updates were applied manually per platform, leading to routine inconsistencies — products showing as in-stock on Amazon when the WooCommerce warehouse system showed zero inventory, and pricing that varied by 15–30% across platforms due to delayed updates. Customer complaints and negative reviews linked to stock misrepresentation were increasing.',
    solution: 'We built RetailSync, a real-time product data layer connecting the WooCommerce database as the master record to the Amazon and Noon seller APIs. Any price or stock change in WooCommerce propagates to all platforms within 90 seconds. Sync failures trigger an instant Slack alert with the failed record and error detail. A daily reconciliation job cross-checks all three platforms and flags any remaining discrepancies for review.',
    techStack: ['WooCommerce API', 'Amazon SP-API', 'Noon Seller API', 'n8n', 'Node.js', 'Slack API'],
    results: [
      { b: '0', s: 'Inventory discrepancies' },
      { b: '<90s', s: 'Propagation time per update' },
      { b: '3', s: 'Platforms synced from one master' },
    ],
  },
  {
    slug: 'guestiq',
    tags: ['Hospitality', 'AI'],
    title: 'GuestIQ',
    client: 'Hotel group, UAE',
    desc: 'AI-powered guest review response system. Personalised, brand-consistent responses to TripAdvisor, Google, and Booking.com reviews.',
    stat: 'Review response: 40% → 98%',
    challenge: 'A UAE hotel group operating four properties was responding to only 40% of its online reviews due to the time required to craft personalised, brand-consistent responses across TripAdvisor, Google, and Booking.com. Management estimates suggested that each human-written response took 12–15 minutes. With 200+ reviews per month across the group, full response coverage would require a part-time dedicated role. Meanwhile, a competitor with near-100% response rates was consistently ranked higher in search results.',
    solution: 'We built GuestIQ, an AI review management system trained on each property\'s brand voice, service standards, and historical responses. New reviews are detected via platform API polling every 30 minutes. The AI generates a personalised, brand-consistent response for each review — acknowledging specific details mentioned, addressing negative feedback constructively, and matching the formality level of the original review. Responses are queued for a one-click human approval before posting, taking under 30 seconds per review.',
    techStack: ['GPT-4o', 'TripAdvisor API', 'Google Business API', 'Booking.com API', 'Next.js', 'PostgreSQL'],
    results: [
      { b: '98%', s: 'Review response rate (was 40%)' },
      { b: '200+', s: 'Reviews handled monthly' },
      { b: '+0.4★', s: 'Average rating improvement' },
    ],
  },
  {
    slug: 'buildright',
    tags: ['Custom Dev'],
    title: 'BuildRight',
    client: 'Construction firm, Romania',
    desc: 'Construction project milestone tracker with automated client communications. Progress updates sent automatically at each milestone.',
    stat: '100% client visibility',
    challenge: 'A Romanian construction firm managing 15–20 simultaneous residential and commercial projects was struggling with client communication. Project managers were supposed to send weekly progress updates to clients but the volume of projects meant updates were often delayed or skipped, leading to client anxiety, inbound enquiries consuming management time, and disputes at handover about what had been communicated. The firm was also losing repeat business to competitors perceived as more transparent.',
    solution: 'We built BuildRight, a project milestone tracking platform tailored to construction workflows. Project managers log milestone completions (foundations complete, frame up, roof on, fit-out, snagging, handover) via a simple mobile-friendly form. Each milestone completion automatically triggers a branded client email with a plain-English progress summary, photos attached, the next milestone target, and an updated projected completion date. Clients can view a live project dashboard via a secure link at any time.',
    techStack: ['Next.js', 'PostgreSQL', 'Resend', 'Vercel', 'Tailwind CSS', 'AWS S3'],
    results: [
      { b: '100%', s: 'Client update coverage' },
      { b: '0', s: 'Handover disputes in 12 months' },
      { b: '89%', s: 'Client repeat/referral rate' },
    ],
  },
  {
    slug: 'solargrid',
    tags: ['Energy', 'IoT'],
    title: 'SolarGrid',
    client: 'Solar farm, Romania',
    desc: 'IoT monitoring system for a 5MW solar farm. Panel-level performance tracking, fault detection, and automated maintenance alerts.',
    stat: 'Fault detection: days → minutes',
    challenge: 'A 5MW solar farm in Romania was relying on daily manual performance reviews of inverter output data to identify underperforming panels and faults. On average, faults went undetected for 2–3 days before a field visit was scheduled, during which time the affected string was generating minimal or no power. Given the revenue model of the farm (feed-in tariff), each day of reduced output had a direct financial cost. The operations team also had no predictive visibility into maintenance requirements.',
    solution: 'We built a panel-level IoT monitoring system that integrates with the farm\'s inverter network and string-level monitoring hardware. Performance data is collected every 5 minutes per string and compared against the expected output model based on current irradiance and temperature conditions. Deviations trigger automated fault classification (soiling, shading, inverter fault, panel degradation), and a maintenance alert is dispatched to the field team with exact string location, estimated output loss, and recommended action.',
    techStack: ['MQTT', 'Python', 'InfluxDB', 'Grafana', 'Twilio SMS', 'OpenWeather API'],
    results: [
      { b: '<15min', s: 'Fault detection time (was 2–3 days)' },
      { b: '5MW', s: 'Farm capacity monitored' },
      { b: '6.2%', s: 'Output recovery from faster response' },
    ],
  },
  {
    slug: 'portalmax',
    tags: ['Real Estate', 'Custom Dev'],
    title: 'PortalMax',
    client: 'Property marketplace, UAE',
    desc: 'Marketplace aggregator for UAE property rentals. Listings syndicated across 8 portals from a single dashboard.',
    stat: '8 portals, one dashboard',
    challenge: 'A UAE property marketplace was manually publishing and maintaining rental listings across 8 platforms including Bayut, PropertyFinder, Dubizzle, Houza, JustProperty, Facebook Marketplace, and two regional portals. The listing team of 4 people spent the majority of their time on repetitive data entry and photo uploads, and the same errors appeared on multiple platforms simultaneously because there was no single source of truth. Portal API changes regularly broke parts of their manual workflow.',
    solution: 'We built PortalMax, a centralised property management and syndication platform. Landlords and agents manage all listing details — description, pricing, photos, availability — in one dashboard. PortalMax maintains API integrations with all 8 portals and syndicates every listing change automatically. Each portal integration is maintained by Tergo Media, meaning API changes are handled without involving the client team. A performance dashboard shows per-portal enquiry volume, helping the team prioritise where to invest.',
    techStack: ['Next.js', 'PostgreSQL', 'Node.js', 'Bayut API', 'PropertyFinder API', 'AWS S3'],
    results: [
      { b: '8', s: 'Portals from one dashboard' },
      { b: '70%', s: 'Listing team time reclaimed' },
      { b: '0', s: 'Cross-portal inconsistencies' },
    ],
  },
  {
    slug: 'logichain',
    tags: ['Logistics', 'Automation'],
    title: 'LogiChain',
    client: 'Freight company, UAE',
    desc: 'Customs document automation for freight forwarding. Bills of lading, certificates, and customs forms generated automatically.',
    stat: 'Document time cut 75%',
    challenge: 'A UAE freight forwarding company was preparing customs documentation — bills of lading, certificates of origin, packing lists, customs declarations — manually for each shipment. A documentation officer was spending 6+ hours per day on document preparation, working from multiple Excel templates and copy-pasting data between forms. Errors in customs documents were causing shipment holds averaging 1.5 days per incident, with direct cost implications for the company and reputational damage with clients.',
    solution: 'We built LogiChain, a document automation platform for freight forwarding operations. Shipment details are entered once into a structured form; the system generates all required customs documents — pre-populated, formatted, and ready for signature — using template logic that handles UAE, EU, and GCC customs requirements. Documents are checked against validation rules before generation to catch errors pre-submission. Completed document sets are automatically emailed to the relevant customs brokers, agents, and clients.',
    techStack: ['Next.js', 'PostgreSQL', 'PDF generation', 'Node.js', 'Resend', 'Tailwind CSS'],
    results: [
      { b: '75%', s: 'Document preparation time cut' },
      { b: '0', s: 'Document-related holds in 6 months' },
      { b: '3min', s: 'Full document set generation time' },
    ],
  },
  {
    slug: 'edupath',
    tags: ['Education', 'Automation'],
    title: 'EduPath',
    client: 'Education provider, Romania',
    desc: 'Student onboarding and scheduling automation. Enrolment triggers welcome sequence, schedule creation, and portal access.',
    stat: 'Onboarding: 3d → 30min',
    challenge: 'A Romanian online education provider was taking an average of 3 business days to fully onboard a new student after enrolment payment — creating the Moodle account, assigning course modules, sending the welcome pack, generating the study schedule, and confirming payment. With 200+ monthly enrolments and a lean admin team, delays were common, negative first-day experiences were generating support tickets, and some students were requesting refunds before their access had even been activated.',
    solution: 'We built an enrolment-triggered automation that fires immediately on confirmed payment. The Moodle account is created and the correct course modules assigned within 60 seconds. A personalised welcome email containing login credentials, the study schedule PDF, and a getting-started video link is sent automatically. A Slack notification goes to the student\'s assigned academic support contact. If any step fails, the admin team is alerted via Slack with a one-click manual override option.',
    techStack: ['Moodle API', 'n8n', 'Resend', 'Stripe Webhooks', 'PostgreSQL', 'Slack API'],
    results: [
      { b: '30min', s: 'Full onboarding (was 3 days)' },
      { b: '200+', s: 'Students onboarded monthly' },
      { b: '91%', s: 'Reduction in onboarding support tickets' },
    ],
  },
  {
    slug: 'primeclinics',
    tags: ['Healthcare', 'Automation'],
    title: 'PrimeClinics',
    client: 'Medical clinics, UAE',
    desc: 'Patient appointment and reminder automation. Bookings, confirmations, reminders, and follow-ups all automated.',
    stat: 'No-shows reduced 41%',
    challenge: 'A UAE medical clinic group operating four sites was experiencing a 28% appointment no-show rate, costing the business an estimated AED 35,000 per month in lost appointment revenue and wasted clinical time. Appointment confirmations were sent manually by reception staff, reminders were inconsistent across sites, and follow-up care instructions were sent only when reception had time. A patient satisfaction survey identified appointment communication as the top pain point.',
    solution: 'We built a full appointment communication automation layer integrated with the clinics\' existing booking system. Patients receive an instant WhatsApp confirmation on booking, a 48-hour reminder with a one-click confirmation or reschedule link, a 2-hour day-of reminder, and automated post-appointment follow-up instructions tailored to the appointment type. Patients who do not confirm their appointment 24 hours in advance are flagged to reception for a manual call. No-show data feeds back into the system to optimise reminder timing.',
    techStack: ['WhatsApp Business API', 'n8n', 'PostgreSQL', 'Resend', 'Twilio', 'Node.js'],
    results: [
      { b: '41%', s: 'Reduction in no-show rate' },
      { b: 'AED 35K', s: 'Monthly revenue recovered' },
      { b: '4', s: 'Clinic sites fully automated' },
    ],
  },
];
