/* eslint-disable */
export interface Project {
  slug: string;
  tags: string[];
  title: string;
  client: string;
  sector: string;
  desc: string;
  stat: string;
  image: string;
  challenge: string;
  solution: string;
  techStack: string[];
  results: { b: string; s: string }[];
  portfolioUrl: string;
}

export const PROJECTS: Project[] = [
  {
    slug: 'bayut-premium-ai-connector',
    tags: ['Real Estate', 'AI', 'Automation', 'CRM'],
    title: 'Bayut Premium AI Connector',
    client: 'Real estate broker · Dubai, UAE',
    sector: 'Real Estate',
    desc: 'A Dubai real estate broker listing properties on Bayut was losing high-intent leads to slow response times. Agents averaged 4 hours to reply to WhatsApp enquiries — manually checking internal inventory.',
    stat: 'Programmatic lead response from live inventory',
    image: '/Images/IMG-41.png',
    challenge: "A Dubai real estate broker listing properties on Bayut was losing high-intent leads to slow response times. Agents averaged 4 hours to reply to WhatsApp enquiries — manually checking internal inventory, drafting replies, and routing to the right colleague. During peak periods the backlog reached hundreds of unanswered messages.",
    solution: "We built a connector between Bayut's lead feed and the broker's internal property inventory. When a lead arrives via WhatsApp, a GPT-4o layer instantly queries the live inventory, matches the enquiry to available listings, and sends a personalised response — prices, photos, availability — within 90 seconds. Hot leads are automatically routed to the right agent in HubSpot with full context attached. No agent needs to touch the lead until it's qualified.",
    techStack: ['GPT-4o', 'Bayut Lead API', 'WhatsApp Business API', 'n8n', 'HubSpot CRM', 'Node.js', 'PostgreSQL'],
    results: [
      { b: '90s', s: 'Average lead response time' },
      { b: '100%', s: 'Responses matched to live internal inventory' },
      { b: '0', s: 'Leads answered without checking inventory manually' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/bayut-premium-ai-connector',
  },
  {
    slug: 'aerolink',
    tags: ['Travel', 'Custom Dev', 'Automation'],
    title: 'AeroLink',
    client: 'Private jet charter · Europe',
    sector: 'Travel',
    desc: 'A European private jet charter operator was handling every booking step manually — availability checks, pricing, contract generation, and payment follow-up. Growth was blocked because each new booking consumed disproportionate ops time.',
    stat: 'All manual booking work eliminated',
    image: '/Images/IMG-42.png',
    challenge: 'A European private jet charter operator was handling every booking step manually — availability checks, pricing, contract generation, and payment follow-up. Growth was blocked because each new booking consumed disproportionate ops time.',
    solution: 'We built a full booking platform with real-time availability, automated quoting, Stripe payment collection, and contract dispatch via Resend. Operations now review exceptions only — the routine flow runs without a human in the loop.',
    techStack: ['Next.js', 'PostgreSQL', 'Stripe', 'Resend', 'Node.js', 'Tailwind CSS'],
    results: [
      { b: '100%', s: 'Manual booking tasks automated' },
      { b: '< 1 day', s: 'Booking-to-confirmation time' },
      { b: '3x', s: 'Capacity handled without new hires' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/aerolink',
  },
  {
    slug: 'remax-gulf',
    tags: ['Real Estate', 'Digital Transformation', 'CRM'],
    title: 'RE/MAX Gulf',
    client: 'Real estate brokerage · Dubai, UAE',
    sector: 'Real Estate',
    desc: "RE/MAX Gulf's brokers were working across HubSpot, WhatsApp, email, and two portal feeds with no unified view of pipeline. Deals were slipping between systems and management had no reliable reporting.",
    stat: '$2.1M pipeline added in 90 days',
    image: '/Images/IMG-43.png',
    challenge: "RE/MAX Gulf's brokers were working across HubSpot, WhatsApp, email, and two portal feeds with no unified view of pipeline. Deals were slipping between systems and management had no reliable reporting.",
    solution: 'We implemented a full HubSpot CRM rollout with WhatsApp Business API connected to deal pipelines, automated follow-up sequences, and a Google Data Studio dashboard pulling from all 12 data sources into one live view.',
    techStack: ['HubSpot', 'n8n', 'Google Data Studio', 'WhatsApp Business API', 'Zapier', 'Google Sheets'],
    results: [
      { b: '$2.1M', s: 'New pipeline in first 90 days' },
      { b: '68%', s: 'Lead follow-up rate improvement' },
      { b: '1 dashboard', s: 'For 12 data sources' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/remax-gulf',
  },
  {
    slug: 'tergo-suite',
    tags: ['Custom Dev', 'Accounting', 'CRM'],
    title: 'Tergo Business Suite',
    client: 'Professional services · Romania',
    sector: 'Custom Dev',
    desc: 'Romanian professional services firms needed a unified system for billing hour tracking, client management, and invoice production compliant with local fiscal requirements. Existing tools were disconnected.',
    stat: 'Full accounting & CRM suite with SharePoint-connected invoicing',
    image: '/Images/IMG-44.png',
    challenge: 'Romanian professional services firms needed a unified system for billing hour tracking, client management, and invoice production compliant with local fiscal requirements. Existing tools were disconnected, required manual data transfer, and had no integration with Microsoft SharePoint where client files lived.',
    solution: 'We built a full accounting and CRM suite tailored to the Romanian market. Users track billable hours per client and project, generate compliant invoices in one click, and sync all documents directly to SharePoint. The CRM layer manages client relationships, contacts, and deal history in the same interface.',
    techStack: ['Next.js', 'Node.js', 'PostgreSQL', 'Microsoft SharePoint API', 'Microsoft Graph API', 'Resend', 'Vercel'],
    results: [
      { b: '1 system', s: 'Replacing 4 disconnected tools' },
      { b: '100%', s: 'Romanian fiscal compliance' },
      { b: '0', s: 'Manual invoice formatting steps' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/tergo-suite',
  },
  {
    slug: 'luxstay',
    tags: ['Travel', 'Automation', 'IoT'],
    title: 'LuxStay',
    client: 'Short-term rentals · Portugal',
    sector: 'Travel',
    desc: 'A Portuguese short-term rental operator was managing listings across Airbnb, Booking.com, and direct bookings with manual calendar sync. Double-bookings happened every fortnight and each one cost hours to resolve.',
    stat: 'Calendar sync errors eliminated completely',
    image: '/Images/IMG-45.png',
    challenge: 'A Portuguese short-term rental operator was managing listings across Airbnb, Booking.com, and direct bookings with manual calendar sync. Double-bookings happened every fortnight and each one cost hours to resolve and damaged reviews.',
    solution: 'We built an n8n automation layer connecting all three platforms via their APIs, with PostgreSQL as the source of truth. Any booking on any channel updates all others within 60 seconds. Resend handles guest communications automatically.',
    techStack: ['Airbnb API', 'Booking.com API', 'n8n', 'PostgreSQL', 'Resend', 'Twilio'],
    results: [
      { b: '0', s: 'Sync errors since launch' },
      { b: '3 platforms', s: 'Unified in real time' },
      { b: '4 hrs/wk', s: 'Ops time reclaimed' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/luxstay',
  },
  {
    slug: 'greenfield-farms',
    tags: ['Agriculture', 'IoT', 'Automation'],
    title: 'GreenField Farms',
    client: 'Crop monitoring · Romania',
    sector: 'Agriculture',
    desc: 'GreenField Farms had no automated monitoring for their 8 crop zones. Soil moisture failures, frost events, and pest pressure were identified through manual field walks — too late to prevent damage.',
    stat: '3 critical crop failures prevented in first season',
    image: '/Images/IMG-46.png',
    challenge: 'GreenField Farms had no automated monitoring for their 8 crop zones. Soil moisture failures, frost events, and pest pressure were identified through manual field walks — too late to prevent damage in two out of three cases.',
    solution: 'We deployed sensor nodes across all zones connected via MQTT to a Python-based monitoring engine. Alerts go out via SMS within minutes of any anomaly. The system also pulls OpenWeather forecasts to flag risk windows 24 hours in advance.',
    techStack: ['MQTT', 'Python', 'InfluxDB', 'Twilio SMS', 'OpenWeather API', 'Resend'],
    results: [
      { b: '3', s: 'Critical failures prevented' },
      { b: '< 5 min', s: 'Alert-to-response time' },
      { b: '8 zones', s: 'Monitored continuously' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/greenfield-farms',
  },
  {
    slug: 'getfastclaim',
    tags: ['Finance', 'AI', 'Automation'],
    title: 'GetFastClaim',
    client: 'Insurance claims · United Kingdom',
    sector: 'Finance',
    desc: 'A UK insurance claims handler was manually extracting data from 200+ PDF documents per day — policy numbers, damage estimates, claimant details — into their internal system. Errors were frequent and the team was at capacity.',
    stat: 'Manual document entry fully eliminated',
    image: '/Images/IMG-47.png',
    challenge: 'A UK insurance claims handler was manually extracting data from 200+ PDF documents per day — policy numbers, damage estimates, claimant details — into their internal system. Errors were frequent and the team was at capacity.',
    solution: 'We built a GPT-4o Vision pipeline that reads incoming claim documents from AWS S3, extracts all structured data with 94% accuracy, and pushes validated records directly to the case management database via n8n.',
    techStack: ['GPT-4o Vision', 'Python', 'AWS S3', 'PostgreSQL', 'n8n', 'Resend'],
    results: [
      { b: '0', s: 'Manual data entry steps' },
      { b: '94%', s: 'Document extraction accuracy' },
      { b: '8x', s: 'Faster claim processing' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/getfastclaim',
  },
  {
    slug: 'law-nexus',
    tags: ['Legal', 'AI', 'Automation'],
    title: 'Law Nexus',
    client: 'Law firm · Milan, Italy',
    sector: 'Legal',
    desc: "Nexus Law's team was tracking 300+ contract renewal and filing deadlines across a spreadsheet maintained by one associate. Two near-misses in a quarter made clear the system was one person leaving away from failure.",
    stat: 'Zero contract renewals missed since launch',
    image: '/Images/IMG-48.png',
    challenge: "Nexus Law's team was tracking 300+ contract renewal and filing deadlines across a spreadsheet maintained by one associate. Two near-misses in a quarter made clear the system was one person leaving away from failure.",
    solution: 'We built a Claude-powered contract monitoring system that reads documents from Google Drive, extracts all key dates and obligations, and triggers reminder sequences via n8n. Every deadline gets a 30-day, 7-day, and 1-day alert.',
    techStack: ['Claude API', 'Python', 'PostgreSQL', 'n8n', 'Resend', 'Google Drive API'],
    results: [
      { b: '0', s: 'Renewals missed' },
      { b: '100%', s: 'Deadline coverage' },
      { b: '3 hrs/wk', s: 'Admin time reclaimed' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/law-nexus',
  },
  {
    slug: 'proptrack',
    tags: ['Real Estate', 'Automation', 'Custom Dev'],
    title: 'PropTrack',
    client: 'Property tech · Singapore',
    sector: 'Real Estate',
    desc: 'A Singapore property tech company was pushing listings to 8 regional portals manually. Mismatched prices, outdated availability, and missing images appeared on portals 24–48 hours after changes.',
    stat: 'Listing sync errors dropped to zero',
    image: '/Images/IMG-49.png',
    challenge: 'A Singapore property tech company was pushing listings to 8 regional portals manually. Mismatched prices, outdated availability, and missing images appeared on portals 24–48 hours after changes, leading to agent complaints and lost enquiries.',
    solution: 'We built a unified listing management API layer using Node.js and PostgreSQL. Any change to a listing propagates to all 8 portals within 60 seconds. Slack alerts notify the ops team of any portal rejection or API failure.',
    techStack: ['Node.js', 'PostgreSQL', 'Bayut API', 'PropertyFinder API', 'n8n', 'Slack API'],
    results: [
      { b: '0', s: 'Listing errors since launch' },
      { b: '8 portals', s: 'Synced from one system' },
      { b: '< 60s', s: 'Cross-portal update time' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/proptrack',
  },
  {
    slug: 'aquapure-industries',
    tags: ['Industrial', 'IoT', 'Automation'],
    title: 'AquaPure Industries',
    client: 'Water treatment plant · Romania',
    sector: 'Industrial',
    desc: "AquaPure's treatment plant relied on a single on-call engineer to monitor process health. Anomalies in chemical dosing, flow rates, and pressure were discovered during shift handovers — sometimes hours after they began.",
    stat: 'Alert-to-response time under 3 minutes',
    image: '/Images/IMG-50.png',
    challenge: "AquaPure's treatment plant relied on a single on-call engineer to monitor process health. Anomalies in chemical dosing, flow rates, and pressure were discovered during shift handovers — sometimes hours after they began affecting output quality.",
    solution: 'We deployed a real-time MQTT monitoring stack feeding InfluxDB, with PagerDuty escalations for critical alerts and Grafana dashboards for shift supervisors. Any out-of-spec reading triggers an alert chain within 3 minutes.',
    techStack: ['MQTT', 'Node.js', 'InfluxDB', 'Twilio SMS', 'PagerDuty', 'Grafana'],
    results: [
      { b: '< 3 min', s: 'Alert-to-response time' },
      { b: '24/7', s: 'Automated monitoring coverage' },
      { b: '0', s: 'Undetected process failures' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/aquapure-industries',
  },
  {
    slug: 'medrecord-ai',
    tags: ['Healthcare', 'AI', 'Automation'],
    title: 'MedRecord AI',
    client: 'Healthcare provider · Italy',
    sector: 'Healthcare',
    desc: 'An Italian healthcare provider was manually processing 500+ patient intake forms, referral letters, and lab results per day. The administrative team was overwhelmed and document-to-system lag was causing delays in care coordination.',
    stat: 'Document processing time cut by 80%',
    image: '/Images/IMG-51.png',
    challenge: 'An Italian healthcare provider was manually processing 500+ patient intake forms, referral letters, and lab results per day. The administrative team was overwhelmed and document-to-system lag was causing delays in care coordination.',
    solution: 'We built a GPT-4o Vision ingestion pipeline reading documents from a secure S3 bucket, extracting structured patient data, and pushing validated records to the EHR via n8n. Resend handles notification workflows for clinical staff.',
    techStack: ['GPT-4o Vision', 'Python', 'AWS S3', 'PostgreSQL', 'n8n', 'Resend'],
    results: [
      { b: '80%', s: 'Processing time reduction' },
      { b: '97%', s: 'Extraction accuracy' },
      { b: '500+', s: 'Documents processed per day' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/medrecord-ai',
  },
  {
    slug: 'novatex-italia',
    tags: ['Agriculture', 'Web', 'Custom Dev'],
    title: 'Novatex Italia',
    client: 'Agricultural machinery · Italy',
    sector: 'Agriculture',
    desc: "Novatex Italia's sales team was fielding hundreds of spec and pricing enquiries by phone and email — all answerable by their catalogues, which customers found impossible to navigate on the web.",
    stat: 'Interactive bale configurator live on novatexitalia.it',
    image: '/Images/IMG-52.png',
    challenge: "Novatex Italia's sales team was fielding hundreds of spec and pricing enquiries by phone and email — all answerable by their catalogues, which customers found impossible to navigate on the web. There was no way to self-configure a machine and get an instant answer.",
    solution: 'We redesigned and built the full novatexitalia.it website in WordPress and developed an interactive PHP-based bale configurator. Customers select machine type, output specs, and accessories to get an instant specification sheet and price indication — no call required.',
    techStack: ['WordPress', 'PHP', 'WooCommerce', 'Custom Configurator (PHP/JS)', 'MySQL', 'Elementor'],
    results: [
      { b: '1 tool', s: 'Replacing 3 PDF catalogues' },
      { b: '0', s: 'Spec queries needing a sales call' },
      { b: 'Real-time', s: 'Pricing output from configurator' },
    ],
    portfolioUrl: 'https://novatexitalia.it',
  },
  {
    slug: 'agri-novatex-worldwide',
    tags: ['Agriculture', 'Web', 'Custom Dev'],
    title: 'Agri Novatex Worldwide',
    client: 'Agricultural machinery · Multi-market',
    sector: 'Agriculture',
    desc: 'Agri Novatex needed a scalable web presence across six markets — South Africa, UK, Australia, Romania, Italy, and the UAE — each requiring localised content, currency, and a bale yield calculator.',
    stat: '6 localised market websites with bale calculators',
    image: '/Images/IMG-54.png',
    challenge: 'Agri Novatex needed a scalable web presence across six markets — South Africa, UK, Australia, Romania, Italy, and the UAE — each requiring localised content, currency, and a bale yield calculator tuned to regional crop types and measurement units.',
    solution: 'We built and maintain a WordPress multisite installation with per-market configuration. Each site has its own domain, localised bale calculator with region-specific crop parameters, and contact routing — all managed from a single WordPress instance.',
    techStack: ['WordPress Multisite', 'PHP', 'MySQL', 'Custom Bale Calculator (PHP/JS)', 'Elementor', 'WPML'],
    results: [
      { b: '6', s: 'Country websites built' },
      { b: '3', s: 'Languages supported' },
      { b: '1 codebase', s: 'Maintained across all markets' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/agri-novatex-worldwide',
  },
  {
    slug: 'deigma',
    tags: ['Custom Dev', 'Web', 'Automation'],
    title: 'Deigma',
    client: 'B2B systems supplier · Italy',
    sector: 'Custom Dev',
    desc: "Deigma's B2B clients needed to configure complex technical systems before requesting a quote, but the process required back-and-forth emails with the technical team. Each configuration cycle averaged 3 days.",
    stat: 'Complex system configurator live at deigma.it',
    image: '/Images/IMG-53.png',
    challenge: "Deigma's B2B clients needed to configure complex technical systems before requesting a quote, but the process required back-and-forth emails with the technical team. Each configuration cycle averaged 3 days and was a bottleneck on the sales pipeline.",
    solution: 'We built the full deigma.it website in WordPress and developed a custom PHP system configurator that guides clients through component selection, validates compatibility rules, and generates a structured quote request automatically — no email required.',
    techStack: ['WordPress', 'PHP', 'MySQL', 'Custom Configurator (PHP/JS)', 'Elementor', 'WPForms'],
    results: [
      { b: '100%', s: 'Configurations submitted as structured quotes' },
      { b: '0', s: 'Manual spec requests by email' },
      { b: '3 min', s: 'Average time to full configuration' },
    ],
    portfolioUrl: 'https://deigma.it/system-configurator/',
  },
  {
    slug: 'supplylink',
    tags: ['Logistics', 'Custom Dev', 'Automation'],
    title: 'SupplyLink',
    client: 'Manufacturing · Romania',
    sector: 'Logistics',
    desc: 'A Romanian manufacturer was producing customer quotes manually — pulling specs from one system, pricing from another, and formatting in Word. Each quote took up to 5 days and errors were common.',
    stat: 'Quote turnaround from 5 days to 6 hours',
    image: '/Images/IMG-56.png',
    challenge: 'A Romanian manufacturer was producing customer quotes manually — pulling specs from one system, pricing from another, and formatting in Word. Each quote took up to 5 days and errors were common, costing credibility with key accounts.',
    solution: 'We built a Next.js quoting platform pulling live product specs and pricing from the ERP, generating branded PDF quotes automatically, and dispatching them via Resend. Sales teams now issue quotes in hours, not days.',
    techStack: ['Next.js', 'PostgreSQL', 'Resend', 'n8n', 'Python', 'Tailwind CSS'],
    results: [
      { b: '5d → 6h', s: 'Quote turnaround time' },
      { b: '3x', s: 'Quotes issued per week' },
      { b: '0', s: 'Manual data entry steps' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/supplylink',
  },
  {
    slug: 'talentflow',
    tags: ['HR', 'Automation', 'CRM'],
    title: 'TalentFlow',
    client: 'HR platform · Multi-market',
    sector: 'HR',
    desc: "A multi-market HR platform's onboarding process required HR, IT, and the line manager to each complete manual steps across 6 separate systems. New hires routinely started without access to tools.",
    stat: 'New hire setup time from 2 days to 45 minutes',
    image: '/Images/IMG-57.png',
    challenge: "A multi-market HR platform's onboarding process required HR, IT, and the line manager to each complete manual steps across 6 separate systems. New hires routinely started without access to tools, costing productivity in their first week.",
    solution: 'We built a trigger-based automation firing when a new hire record is created in BambooHR — provisioning accounts, creating Notion onboarding workspaces, setting up calendar events, and posting the welcome brief to Slack — all within 45 minutes.',
    techStack: ['BambooHR API', 'Slack API', 'Notion API', 'Google Calendar API', 'n8n', 'Resend'],
    results: [
      { b: '2d → 45min', s: 'New hire setup time' },
      { b: '0', s: 'Manual IT provisioning steps' },
      { b: '6 systems', s: 'Updated automatically on hire' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/talentflow',
  },
  {
    slug: 'skyroute',
    tags: ['Travel', 'Custom Dev', 'Automation'],
    title: 'SkyRoute',
    client: 'Flight operations · Switzerland',
    sector: 'Travel',
    desc: 'A Swiss flight operations company was scheduling crew, aircraft, and ground services across a mix of spreadsheets and email threads. Conflicts were discovered at the last minute and resolving them required hours of coordinator time.',
    stat: 'All manual scheduling work eliminated',
    image: '/Images/IMG-58.png',
    challenge: 'A Swiss flight operations company was scheduling crew, aircraft, and ground services across a mix of spreadsheets and email threads. Conflicts were discovered at the last minute and resolving them required hours of coordinator time.',
    solution: 'We built a Next.js scheduling platform with real-time conflict detection, automated crew notifications via Resend, and a Vercel-hosted ops dashboard. Planners now see the full operation in one view and are alerted to any constraint before it becomes a problem.',
    techStack: ['Next.js', 'PostgreSQL', 'Node.js', 'Resend', 'Tailwind CSS', 'Vercel'],
    results: [
      { b: '100%', s: 'Scheduling tasks automated' },
      { b: 'Zero', s: 'Scheduling conflicts since launch' },
      { b: '2 hrs/day', s: 'Ops time reclaimed per planner' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/skyroute',
  },
  {
    slug: 'ranjet',
    tags: ['Custom Dev', 'Mobile', 'Web'],
    title: 'Ranjet — Restaurants & App',
    client: 'Restaurant group · Multi-market',
    sector: 'Custom Dev',
    desc: "Ranjet's restaurant group was taking reservations through third-party platforms that charged per-cover fees and gave no ownership of guest data. There was no branded mobile presence.",
    stat: 'Native iOS & Android app with direct reservations',
    image: '/Images/IMG-55.png',
    challenge: "Ranjet's restaurant group was taking reservations through third-party platforms that charged per-cover fees and gave no ownership of guest data. There was no branded mobile presence and no direct channel to communicate with returning guests.",
    solution: 'We built a Flutter mobile app for iOS and Android alongside a web booking experience for all Ranjet venues. Guests book directly, earn loyalty points, and receive personalised offers — all managed from a single backend with no third-party fees.',
    techStack: ['Flutter', 'Dart', 'Node.js', 'PostgreSQL', 'Resend', 'Stripe', 'Vercel'],
    results: [
      { b: 'iOS + Android', s: 'Platforms shipped' },
      { b: '0', s: 'Third-party booking fees per cover' },
      { b: '1 app', s: 'For all venues and reservations' },
    ],
    portfolioUrl: 'https://tergomedia.com/portfolio/ranjet',
  },
];
